// Допустимые типы: role | weapon | trap | character | modifier | defense | stance | effect | intervention | aoe | action | aura
const CARDS = [

  // ── РОЛИ ─────────────────────────────────────────────────────────
  // Мета-карты, обозначающие сторону игрока. В колоде не участвуют —
  // выдаются перед раздачей.
  {
    id: 200,
    title: "Ниндзя",
    enTitle: "Ninja",
    titleBgColor: "#0D233C",
    types: ["role"],
    qty: 4,
    group: "role",
    icons: [],
    tags: ["toPrint"],
    desc: "",
    enDesc: "",
    img: "cards/card_role_ninja.png"
  },
  {
    id: 201,
    title: "Самурай",
    enTitle: "Samurai",
    titleBgColor: "#891511",
    types: ["role"],
    qty: 2,
    group: "role",
    icons: [],
    tags: ["toPrint"],
    desc: "",
    enDesc: "",
    img: "cards/card_role_samurai.png"
  },
  {
    id: 202,
    title: "Самурай",
    enTitle: "Samurai",
    titleBgColor: "#891511",
    types: ["role"],
    qty: 1,
    group: "role",
    icons: [],
    tags: ["toPrint"],
    desc: "",
    enDesc: "",
    img: "cards/card_role_samurai_first.png"   // знамя I: с этого самурая начинается партия и каждый раунд
  },
  {
    id: 203,
    title: "Placeholder",
    enTitle: "Placeholder",
    titleBgColor: "#891511",
    types: ["role"],
    qty: 1,
    group: "role",
    icons: [],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_todo_white.png"
  },

  // ── ОРУЖИЕ (стр. 1–5) ────────────────────────────────────────────
  {
    id: 1,
    title: "Катана",
    enTitle: "Katana",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2"],
    tags: [],
    desc: "При наличии стойки вы наносите на 1 рану больше.",
    enDesc: "While you hold a Stance, deal 1 extra wound.",
    img: "cards/card_2_katana.png"
  },
  {
    id: 2,
    title: "Сюко",
    enTitle: "Shuko",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg1", "charctx"],
    tags: ["toPrint"],
    desc: "Любимое оружие {Усивака}.",
    enDesc: "Favourite weapon of {Ushiwaka}.",
    img: "cards/card_1_syuko.png"
  },
  {
    id: 3,
    title: "Канабо",
    enTitle: "Kanabo",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg3", "charctx"],
    tags: ["toPrint"],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.[NL]Любимое оружие {Сайго}.",
    enDesc: "On a successful attack, the target discards a random card.[NL]Favourite weapon of {Saigo}.",
    img: "cards/card_3_kanabo.png"
  },
  {
    id: 4,
    title: "Боккэн",
    enTitle: "Bokken",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg0"],
    tags: [],
    desc: "Вы берёте карту из колоды для себя или союзника в случае успешной атаки.",
    enDesc: "On a successful attack, you or an ally draws a card.",
    img: "cards/card_4_bokken.png"
  },
  {
    id: 5,
    title: "Кинжал предателя",
    enTitle: "Traitor's Dagger",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg1", "rolectx"],
    tags: [],
    desc: "В стойке {ассасина} наносит на одну рану больше.[NL]От удара {ниндзи} нельзя защититься, и он игнорирует ловушки.",
    enDesc: "In the {Assassin} stance, deals 1 extra wound.[NL]A {Ninja}'s strike cannot be defended and ignores Traps.",
    img: "cards/card_5_kinzhal_predatelya.png"
  },
  {
    id: 6,
    title: "Боевой веер",
    enTitle: "War Fan",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2", "charctx"],
    iconsOr: ["ranged", "dmg1"],
    tags: ["toPrint"],
    desc: "Любимое оружие {Манасэ}.",
    enDesc: "Favourite weapon of {Manase}.",
    img: "cards/card_6_boevoy_veer.png"
  },
  {
    id: 7,
    title: "Кусаригама",
    enTitle: "Kusarigama",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2", "charctx"],
    iconsOr: ["complexity2", "dmg1"],
    tags: ["toPrint"],
    desc: "Любимое оружие {Хандзо}.",
    enDesc: "Favourite weapon of {Hanzo}.",
    img: "cards/card_7_kusarigama.png"
  },
  {
    id: 8,
    title: "Вакидзаси",
    enTitle: "Wakizashi",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_8_wakizashi.png"
  },
  {
    id: 9,
    title: "Шипастый щит",
    enTitle: "Spiked Shield",
    types: ["weapon", "defense"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg1", "defense"],
    tags: [],
    desc: "Можно использовать как карту Защиты. В стойке {щитоносца} наносит на одну рану больше.",
    enDesc: "May be played as a Defense card. In the {Shield Bearer} stance, deals 1 extra wound.",
    img: "cards/card_9_shipastyy_shchit.png"
  },
  {
    id: 10,
    title: "Тонфа",
    enTitle: "Tonfa",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    enDesc: "On a successful attack, the target discards a random card.",
    img: "cards/card_10_tonfa.png"
  },
  {
    id: 11,
    title: "Кама",
    enTitle: "Kama",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg3"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_11_kama.png"
  },
  {
    id: 12,
    title: "Меч сёгуна",
    enTitle: "Shogun's Blade",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg3"],
    tags: ["trash"],
    desc: "Только Сёгун может проводить прямую атаку этим оружием. Можно сыграть как вмешательство, чтобы передать эту карту Сёгуну в обмен на другую в закрытую.",
    enDesc: "Only the Shogun may make a direct attack with this weapon. May be played as an Intervention to hand this card to the Shogun in exchange for another, face down.",
    img: "cards/card_12_mech_syoguna.png"
  },
  {
    id: 13,
    title: "Тэккокаги",
    enTitle: "Tekkokagi",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg4"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_13_tekko_kagi.png"
  },
  {
    id: 14,
    title: "Нунчаки",
    enTitle: "Nunchaku",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_14_nunchaki.png"
  },
  {
    id: 15,
    title: "Танто",
    enTitle: "Tanto",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_15_mango.png"
  },
  {
    id: 16,
    title: "Тэкко",
    enTitle: "Tekko",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg3"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_16_mekko.png"
  },
  {
    id: 17,
    title: "Оно",
    enTitle: "Ono",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg1"],
    tags: ["trash"],
    desc: "",
    enDesc: "",
    img: "cards/card_17_ono.png"
  },
  {
    id: 317,
    title: "Ната",
    enTitle: "Nata",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["complexity1", "dmg1"],
    tags: ["trash"],
    desc: "",
    enDesc: "",
    img: "cards/card_nata.png"
  },
  {
    id: 18,
    title: "Сай",
    enTitle: "Sai",
    types: ["weapon", "defense"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2", "defense"],
    tags: [],
    desc: "Это оружие можно использовать как Защиту.",
    enDesc: "This weapon may be played as a Defense.",
    img: "cards/card_18_say.png"
  },
  {
    id: 1018,
    title: "Манжи Сай",
    enTitle: "Manji Sai",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg2"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_manji_sai.png"
  },
  {
    id: 19,
    title: "Явара",
    enTitle: "Yawara",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    enDesc: "On a successful attack, the target discards a random card.",
    img: "cards/card_23_yavara.png"
  },
  {
    id: 20,
    title: "Боевой веер",
    enTitle: "War Fan",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    iconsOr: ["complexity1", "dmg2", "poison"],
    tags: ["poison", "toPrint"],
    desc: "",
    enDesc: "",
    img: "cards/card_6_boevoy_veer.png"
  },
  {
    id: 21,
    title: "Сай",
    enTitle: "Sai",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison"],
    desc: "",
    enDesc: "",
    img: "cards/card_18_say.png"
  },
  {
    id: 22,
    title: "Дзюттэ",
    enTitle: "Jutte",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity1", "dmg1"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_21_dzyutte.png"
  },
  {
    id: 23,
    title: "Нунти Бо",
    enTitle: "Nunti Bo",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg2", "charctx"],
    tags: ["toPrint"],
    desc: "{Древковое}[NL]Любимое оружие {Таранага}.",
    enDesc: "{Polearm}[NL]Favourite weapon of {Taranaga}.",
    img: "cards/card_22_nunti.png"
  },
  {
    id: 24,
    title: "Бо",
    enTitle: "Bo",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg1", "charctx"],
    tags: ["toPrint"],
    desc: "{Древковое} Атакуемый игрок теряет стойку в случае успешной атаки; у {Сайго} стойку отнять нельзя.[NL]Любимое оружие {Норио}.",
    enDesc: "{Polearm} On a successful attack, the target loses their Stance; {Saigo} keeps his.[NL]Favourite weapon of {Norio}.",
    img: "cards/card_24_bo.png"
  },
  {
    id: 25,
    title: "Нодати",
    enTitle: "Nodachi",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg3"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_25_nodati.png"
  },
  {
    id: 26,
    title: "Кёкэцусёгэ",
    enTitle: "Kyoketsu-shoge",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg2", "charctx"],
    tags: ["toPrint"],
    desc: "В случае успешной атаки вы забираете карту из руки врага.[NL]Любимое оружие {Така}.",
    enDesc: "On a successful attack, take a card from the enemy's hand.[NL]Favourite weapon of {Taka}.",
    img: "cards/card_26_kyoketsusyoge.png"
  },
  {
    id: 27,
    title: "Манрики",
    enTitle: "Manriki",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg1"],
    tags: [],
    desc: "В случае успешной атаки вы забираете карту из руки врага.",
    enDesc: "On a successful attack, take a card from the enemy's hand.",
    img: "cards/card_27_manriki.png"
  },
  {
    id: 28,
    title: "Нагината",
    enTitle: "Naginata",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity_any", "dmg2"],
    tags: ["toPrint"],
    desc: "{Древковое} Бьёт при любой сложности атаки.",
    enDesc: "{Polearm} Strikes at any attack complexity.",
    img: "cards/card_28_naginata.png"
  },
  {
    id: 29,
    title: "Яри",
    enTitle: "Yari",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg1"],
    iconsOr: ["ranged", "dmg1"],
    tags: ["toPrint"],
    desc: "{Древковое} В стойке {всадника} наносит на одну рану больше.",
    enDesc: "{Polearm} In the {Horseman} stance, deals 1 extra wound.",
    img: "cards/card_29_yari.png"
  },
  {
    id: 30,
    title: "Камаяри",
    enTitle: "Kamayari",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg1"],
    tags: ["toPrint"],
    desc: "{Древковое} В стойке {всадника} наносит на одну рану больше.",
    enDesc: "{Polearm} In the {Horseman} stance, deals 1 extra wound.",
    img: "cards/card_31_kamayari.png"
  },
  {
    id: 31,
    title: "Яри",
    enTitle: "Yari",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["complexity2", "dmg1", "poison"],
    iconsOr: ["ranged", "dmg1", "poison"],
    tags: ["poison", "toPrint"],
    desc: "{Древковое} В стойке {всадника} наносит на одну рану больше.",
    enDesc: "{Polearm} In the {Horseman} stance, deals 1 extra wound.",
    img: "cards/card_29_yari.png"
  },
  {
    id: 32,
    title: "Сюрикен",
    enTitle: "Shuriken",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_34_syuriken.png"
  },
  {
    id: 33,
    title: "Дайкю",
    enTitle: "Daikyu",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg2"],
    tags: [],
    desc: "В стойке {лучника} наносит на одну рану больше.",
    enDesc: "In the {Archer} stance, deals 1 extra wound.",
    img: "cards/card_33_dayku.png"
  },
  {
    id: 1033,
    title: "Тэппо Юми",
    enTitle: "Teppo Yumi",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg2"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_teppo_umi.png"
  },
  {
    id: 34,
    title: "Сюрикен",
    enTitle: "Shuriken",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison", ],
    desc: "",
    enDesc: "",
    img: "cards/card_34_syuriken.png"
  },
  {
    id: 35,
    title: "Кунай",
    enTitle: "Kunai",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    iconsOr: ["complexity2", "dmg2"],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_36_kunay.png"
  },
  {
    id: 36,
    title: "Бумеранг",
    enTitle: "Boomerang",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "В случае успешной атаки это оружие возвращается вам в руку.",
    enDesc: "On a successful attack, this weapon returns to your hand.",
    img: "cards/card_37_bumerang.png"
  },
  {
    id: 37,
    title: "Дайкю",
    enTitle: "Daikyu",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg2", "poison"],
    tags: ["poison"],
    desc: "В стойке {лучника} наносит на одну рану больше.",
    enDesc: "In the {Archer} stance, deals 1 extra wound.",
    img: "cards/card_33_dayku.png"
  },
  {
    id: 38,
    title: "Макибиши",
    enTitle: "Makibishi",
    types: ["weapon", "trap"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "trap", "charctx"],
    tags: ["toPrint"],
    desc: "Можно использовать как ловушку, которая наносит одну рану атакующему в ответ.[NL]Любимое оружие {Иё}.",
    enDesc: "May be played as a Trap that deals 1 wound back to the attacker.[NL]Favourite weapon of {Iyo}.",
    img: "cards/card_38_makibishi.png"
  },
  {
    id: 39,
    title: "Дротик с ядом",
    enTitle: "Poison Dart",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg0", "poison", "charctx"],
    tags: ["toPrint", "poison"],
    desc: "Атака игнорирует ловушки и защиту, и вы берёте карту из колоды.[NL]Любимое оружие {Минамото}.",
    enDesc: "This attack ignores Traps and Defense, and you draw a card.[NL]Favourite weapon of {Minamoto}.",
    img: "cards/card_39_drotik_s_yadom.png"
  },
  {
    id: 40,
    title: "Кунай",
    enTitle: "Kunai",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    iconsOr: ["complexity1", "dmg2", "poison"],
    tags: ["poison"],
    desc: "",
    enDesc: "",
    img: "cards/card_36_kunay.png"
  },
  {
    id: 318,
    title: "Утинэ",
    enTitle: "Uchine",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "TODO: механика возврата. Задумано — после успешной атаки оружие возвращается вам в руку по шнуру, но любой игрок может вмешаться и перерезать шнур. Развести с Бумерангом #36, у которого возврат безусловный и без контригры.",
    enDesc: "TODO: the return mechanic. The intent — after a successful attack the weapon comes back to your hand along its cord, but any player may intervene and cut the cord. Needs separating from the Boomerang #36, whose return is unconditional and has no counterplay.",
    img: "cards/card_318_utine.png"
  },
  {
    id: 319,
    title: "Содэгарами",
    enTitle: "Sodegarami",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["complexity2", "dmg1"],
    tags: ["toPrint"],
    desc: "{Древковое} TODO: захват вместо урона. Задумано — вместо ран забирает карту из руки цели: рукавоплётом валили, не убивая. Развести с Манрики #27 и Кёкэцусёгэ #26, которые уже забирают карту при успешной атаке.",
    enDesc: "{Polearm} TODO: capture instead of damage. The intent — it takes a card from the target's hand instead of dealing wounds: the sleeve entangler brought a man down without killing him. Needs separating from the Manriki #27 and the Kyoketsu-shoge #26, which already take a card on a successful attack.",
    img: "cards/card_319_sodegarami.png"
  },
  {
    id: 320,
    title: "Фукия",
    enTitle: "Fukiya",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "TODO: тишина. Задумано — выстрел не будит ловушку и не тратит попытку атаки. Решить, что из двух оставить: обе сразу почти наверняка слишком сильно.",
    enDesc: "TODO: silence. The intent — the shot neither triggers a Trap nor uses up an attack. Decide which of the two to keep: both at once is almost certainly too strong.",
    img: "cards/card_320_fukiya.png"
  },
  {
    id: 321,
    title: "Сайхай",
    enTitle: "Saihai",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["complexity1", "dmg0"],
    tags: [],
    desc: "TODO: это не оружие. Сила атаки 0 — ударить им нельзя вообще. Задумано, что жезл распоряжается: задаёт, кто берёт карты или ходит следующим. Решить, остаётся ли карта в группе оружия или уезжает в действия.",
    enDesc: "TODO: this is not a weapon. Attack power 0 — it cannot strike at all. The intent is that the baton commands: it decides who draws cards or who acts next. Decide whether the card stays in the weapon group or moves to actions.",
    img: "cards/card_321_saihai.png"
  },

  // ── ЛОВУШКИ (стр. 7) ─────────────────────────────────────────────
  {
    id: 41,
    title: "Силок",
    enTitle: "Snare",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: [],
    tags: [],
    desc: "Вы забираете у атакующего две карты.",
    enDesc: "Take two cards from the attacker.",
    img: "cards/card_41_silok.png"
  },
  {
    id: 42,
    title: "Чучело",
    enTitle: "Straw Decoy",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: [],
    tags: [],
    desc: "Атака не проходит, защищающийся берёт 2 карты из колоды.",
    enDesc: "The attack fails and the defender draws 2 cards.",
    img: "cards/card_42_chuchelo.png"
  },
  {
    id: 43,
    title: "Капкан",
    enTitle: "Bear Trap",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: ["effect8"],
    tags: ["toPrint"],
    desc: "Атакующий получает две раны от владельца ловушки. Затем эта карта переходит на него эффектом: сложность атак по нему всегда равна 1 — Доспех и другие повышения сложности не спасают.",
    enDesc: "The attacker takes two wounds from the Trap's owner. Then this card moves onto them as an Effect: attacks against them are always complexity 1 — Armor and other complexity increases do not help.",
    img: "cards/card_43_kapkan.png"
  },
  {
    id: 45,
    title: "Поганка",
    enTitle: "Death Cap",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Атакующий отравляется ядом, но если он уже отравлен, то вы наносите ему три раны.",
    enDesc: "The attacker is Poisoned; if they are Poisoned already, deal them 3 wounds instead.",
    img: "cards/card_45_poganka.png"
  },
  {
    id: 47,
    title: "Оскорбление",
    enTitle: "Insult",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: ["rolectx", "effect8"],
    tags: ["toPrint"],
    desc: "Вы оскорбляете атакующего. Для {самурая} это хуже смерти, и он получает эту карту как эффект бешенства, сбрасывая каждый раз карту при прямой атаке.",
    enDesc: "You insult the attacker. For a {Samurai} this is worse than death: they take this card as an Effect of rage and must discard a card with every direct attack.",
    img: "cards/card_47_oskorblenie.png"
  },
  {
    id: 1048,
    title: "Дыхание Феникса",
    enTitle: "Phoenix Breath",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: [],
    tags: [],
    desc: "Если вы остались в живых после атаки, восстановите все жетоны жизни.",
    enDesc: "If you survive the attack, restore all your life.",
    img: "cards/card_phoenix_breath.png"
  },
  {
    id: 1049,
    title: "Колотые раны",
    enTitle: "Puncture Wounds",
    types: ["trap", "effect"],
    qty: 2,
    group: "trap",
    icons: ["effect8"],
    tags: [],
    desc: "Переходит эффектом на атакующего, и он лишается возможности использовать оружие для прямых атак.",
    enDesc: "Passes to the attacker as an Effect: they can no longer use weapons for direct attacks.",
    img: "cards/card_glass_wounds.png"
  },

  // ── ЗАЩИТА (стр. 8) ──────────────────────────────────────────────
  {
    id: 48,
    title: "Защита",
    enTitle: "Parry",
    types: ["defense"],
    qty: 8,
    group: "defense",
    icons: [],
    tags: [],
    desc: "",
    enDesc: "",
    img: "cards/card_48_zashchita.png"
  },
  {
    id: 49,
    title: "Скрытый кинжал",
    enTitle: "Hidden Dagger",
    types: ["defense"],
    qty: 3,
    group: "defense",
    icons: ["hpctx"],
    tags: [],
    desc: "Атакующий получает 1 рану от вас. {На пороге вашей смерти} враг получает 3 раны.[NL]{При наличии ловушки} вы наносите ещё на одну рану больше.",
    enDesc: "The attacker takes 1 wound from you. {At death's door} the enemy takes 3 wounds instead.[NL]{With a Trap in play} deal 1 more wound.",
    img: "cards/card_49_skrytyy_kinzhal.png"
  },
  {
    id: 50,
    title: "Ядовитые наручи",
    enTitle: "Venom Bracers",
    types: ["defense"],
    qty: 2,
    group: "defense",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Атакующий получает отравление ядом.",
    enDesc: "The attacker becomes Poisoned.",
    img: "cards/card_50_yadovitye_naruchi.png"
  },
  {
    id: 51,
    title: "Вовремя",
    enTitle: "Just in Time",
    types: ["defense"],
    qty: 3,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Вы также берёте карту из колоды.",
    enDesc: "You also draw a card.",
    img: "cards/card_52_idealnyy_moment.png"
  },
  {
    id: 52,
    title: "Чудо Бенкэя",
    enTitle: "Benkei's Miracle",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["charctx"],
    tags: ["toPrint"],
    desc: "Вы можете выбрать сколько ран вы хотите получить при атаке, и за каждую рану (не более трёх) берёте карту из колоды.[NL]{Усивака} также забирает оружие атакующего себе в руку.",
    enDesc: "Choose how many wounds you take from this attack, and draw a card for each wound taken (no more than three).[NL]{Ushiwaka} also takes the attacker's weapon into hand.",
    img: "cards/card_53_vyderzka_samuray.png"
  },
  {
    id: 53,
    title: "Карманник",
    enTitle: "Pickpocket",
    types: ["defense"],
    qty: 2,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Вы также забираете у атакующего случайную карту.",
    enDesc: "You also take a random card from the attacker.",
    img: "cards/card_51_karmannik.png"
  },
  {
    id: 54,
    title: "Ошеломление",
    enTitle: "Stagger",
    types: ["defense"],
    qty: 2,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Атакующий сбрасывает случайную карту.[NL]В стойке {щитоносца} вы берёте 1 карту из колоды.",
    enDesc: "The attacker discards a random card.[NL]In the {Shield Bearer} stance, draw a card.",
    img: "cards/card_54_oshelomlenie.png"
  },
  {
    id: 55,
    title: "Захват",
    enTitle: "Seize",
    types: ["defense"],
    qty: 3,
    group: "defense",
    icons: ["charctx"],
    tags: ["toPrint"],
    desc: "Вы забираете неметательное оружие врага себе в руку; {Хандзо} забирает любое, в том числе метательное.[NL]{При наличии стойки} вы берёте дополнительно карту из колоды.",
    enDesc: "Take the enemy's non-thrown weapon into your hand; {Hanzo} takes any weapon, thrown ones included.[NL]{With a Stance in play} also draw a card.",
    img: "cards/card_55_zakhvat.png"
  },
  {
    id: 44,
    title: "Рикошет",
    enTitle: "Ricochet",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Атака не проходит и обращается обратно, равная базовой силе оружия. Атакующий может защититься от рикошета.",
    enDesc: "The attack fails and rebounds at the weapon's base power. The attacker may defend against the ricochet.",
    img: "cards/card_44_rikoshet.png"
  },
  {
    id: 56,
    title: "Блок",
    enTitle: "Block",
    types: ["intervention", "defense"],
    qty: 3,
    group: "intervention",
    icons: ["defense"],
    tags: ["toPrint"],
    desc: "Можно сыграть в любой момент за любого игрока.",
    enDesc: "May be played at any time, for any player.",
    img: "cards/card_56_blok.png"
  },

  // ── СТОЙКИ (стр. 9) ──────────────────────────────────────────────
  {
    id: 57,
    title: "Тень",
    enTitle: "Shadow",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: [],
    tags: [],
    desc: "Вы считаетесь убитым для других игроков весь раунд, но в начале своего хода сбрасываете эту стойку.",
    enDesc: "You count as dead to the other players for the whole round, but you discard this Stance at the start of your turn.",
    img: "cards/card_57_ten.png"
  },
  {
    id: 58,
    title: "Всадник",
    enTitle: "Horseman",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "Сложность атак по вам увеличивается на 1. Ваше оружие берёт сложность на 1 больше. Атакуя сложность 1, вы наносите на 1 рану больше.",
    enDesc: "Attacks against you are 1 harder. Your weapon handles 1 more complexity. Attacking complexity 1, you deal 1 extra wound.",
    img: "cards/card_58_vsadnik.png"
  },
  {
    id: 59,
    title: "Лотос",
    enTitle: "Lotus",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "При выставлении восстановить два жетона жизни.[NL]Перед каждой фазой набора вы можете: восстановить жетон жизни любому игроку {ИЛИ} взять карту из колоды.",
    enDesc: "When played, restore 2 life.[NL]Before each draw phase you may: restore 1 life to any player {OR} draw a card.",
    img: "cards/card_59_lotos.png"
  },
  {
    id: 60,
    title: "Щитоносец",
    enTitle: "Shield Bearer",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "Каждый раз при прямой атаке по вам снижаете урон на один. Дополнительно можете скинуть карту с руки за каждое снижение урона (не менее 1).[NL]Каждый раз, используя защиту, вы берёте одну карту из колоды.",
    enDesc: "Reduce every direct attack against you by 1 wound. You may discard a card from your hand for each further reduction (never below 1).[NL]Whenever you play a Defense, draw a card.",
    img: "cards/card_60_shchitonosec.png"
  },
  {
    id: 61,
    title: "Мастер боя",
    enTitle: "Blade Master",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "При совершении атаки можете выбрать нанести одну рану больше {ИЛИ} взять одну карту из колоды.[NL]{Совершая успешно прямую атаку} восстановите себе 1 жетон жизни.",
    enDesc: "When you attack, choose: deal 1 extra wound {OR} draw a card.[NL]{On a successful direct attack} restore 1 life.",
    img: "cards/card_61_master_boya.png"
  },
  {
    id: 62,
    title: "Капеллан",
    enTitle: "Chaplain",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: ["rolectx"],
    tags: [],
    desc: "Раз в свой ход вы можете: восстановить жетон жизни любому игроку -ИЛИ- снять яд или один эффект любому игроку, сбросив карту.[NL]{Самураи} не обязаны скидывать карту.",
    enDesc: "Once per turn you may: restore 1 life to any player -OR- discard a card to clear Poison or one Effect from any player.[NL]{Samurai} do not have to discard.",
    img: "cards/card_62_kapellan.png"
  },
  {
    id: 63,
    title: "Ассасин",
    enTitle: "Assassin",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: ["rolectx"],
    tags: [],
    desc: "При атаке по врагу вы можете: сделать вашу атаку отравленной ядом -ИЛИ- сбросив 2 карты, сделать врага беззащитным от атаки.[NL]{Ниндзя} обязаны скинуть лишь 1 карту.[NL]{Убив игрока} возьмите 2 карты из колоды. ",
    enDesc: "When you attack an enemy you may: make your attack Poisoned -OR- discard 2 cards to leave the enemy defenseless against it.[NL]{Ninja} discard only 1 card.[NL]{On killing a player} draw 2 cards.",
    img: "cards/card_63_assassin.png"
  },
  {
    id: 1164,
    title: "Кэцубан",
    enTitle: "Ketsuban",
    types: ["stance"],
    qty: 1,
    group: "stance",
    tags: ["toPrint"],
    desc: "В момент получения ран от оружия вы можете выбрать союзника, согласного с вами разделить в любой пропорции полученные раны.",
    enDesc: "When you take wounds from a weapon, you may choose a willing ally to share those wounds with you in any split.",
    img: "cards/card_1164_ketsuban.png",
  },
  {
    id: 1165,
    title: "Мусин",
    enTitle: "Mushin",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["hpctx"],
    tags: ["toPrint"],
    desc: "{При полном здоровье} совершая прямые атаки вы берёте 2 карты из колоды.[NL]{На пороге смерти} ваши атаки наносят дополнительно 2 раны.",
    enDesc: "{At full health} draw 2 cards when you make a direct attack.[NL]{At death's door} your attacks deal 2 extra wounds.",
    img: "cards/card_musin.png",
  },
  {
    id: 1166,
    title: "Лучник",
    enTitle: "Archer",
    types: ["stance"],
    qty: 1,
    group: "stance",
    tags: [],
    desc: "Ваши метательные атаки наносят +1 рану.[NL]Совершив успешную атаку по игроку с ловушкой, вы берёте 1 карту из колоды.",
    enDesc: "Your thrown attacks deal +1 wound.[NL]On a successful attack against a player who has a Trap, draw a card.",
    img: "cards/card_archer.png",
  },
  // ── МОДИФИКАТОРЫ (стр. 10–11) ─────────────────────────────────────
  {
    id: 64,
    title: "Флакон яда",
    enTitle: "Vial of Poison",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["poison"],
    tags: ["poison", "toPrint"],
    desc: "Ваша атака теперь накладывает отравление и наносит на 1 рану больше.",
    enDesc: "Your attack now inflicts Poison and deals 1 extra wound.",
    img: "cards/card_64_flakon_yada.png"
  },
  {
    id: 65,
    title: "Тамасэгири",
    enTitle: "Tameshigiri",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Ваша атака наносит на одну рану больше.",
    enDesc: "Your attack deals 1 extra wound.",
    img: "cards/card_65_tochilo.png"
  },
  {
    id: 66,
    title: "Инь и Ян",
    enTitle: "Yin and Yang",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "Дальность и сила атаки меняются местами.",
    enDesc: "Swap the range and the power of the attack.",
    img: "cards/card_66_in_i_yan.png"
  },
  {
    id: 67,
    title: "Удар тени",
    enTitle: "Shadow Strike",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["rolectx"],
    tags: [],
    desc: "Ваша атака игнорирует ловушки и от неё невозможно защититься.[NL]{Ниндзя} наносят на 1 рану больше.[NL]{Самураи} штрафуются сбросом карты.",
    enDesc: "Your attack ignores Traps and cannot be defended.[NL]{Ninja} deal 1 extra wound.[NL]{Samurai} pay the price of a discarded card.",
    img: "cards/card_67_udar_teni.png"
  },
  {
    id: 68,
    // Было «Выпад» — переименована 14.09.2026, чтобы не путаться с
    // пометкой «выпад» (thrust, раны мимо атаки). Фумикоми 踏み込み —
    // шаг-впрыгивание из кэндо, которым достают дальнюю цель.
    title: "Фумикоми",
    enTitle: "Lunge",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["toPrint"],
    desc: "+1 к силе атаки. Ваше оружие берёт сложность на 2 больше.[NL]{При наличии стойки} наносите ещё на 1 рану больше.",
    enDesc: "+1 attack power. Your weapon handles 2 more complexity.[NL]{With a Stance in play} deal 1 more wound.",
    img: "cards/card_68_vypad.png"
  },
  {
    id: 69,
    title: "Поступь ветра",
    enTitle: "Wind Step",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "От вашей атаки невозможно защититься, однако ловушки продолжают действовать. (ушло в удар тени)",
    enDesc: "Your attack cannot be defended, but Traps still work. (merged into Shadow Strike)",
    img: "cards/card_69_postup_vetra.png"
  },
  {
    id: 70,
    title: "Гнев сёгуна",
    enTitle: "Shogun's Wrath",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Атаку можно провести даже по игроку при смерти.",
    enDesc: "This attack may be made even against a player at death's door.",
    img: "cards/card_70_gnev_syoguna.png"
  },
  {
    id: 71,
    title: "Кинжал похищения",
    enTitle: "Thirsting Blade",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["charctx"],
    tags: ["toPrint"],
    desc: "В случае успешной атаки вы восстанавливаете себе столько жетонов жизни, сколько нанесли ран.[NL]{Така} вместо жетонов жизни может забрать у цели столько же карт из руки.",
    enDesc: "On a successful attack, restore as much life as the wounds you dealt.[NL]{Taka} may instead take that many cards from the target's hand.",
    img: "cards/card_71_celebnyy_klinok.png"
  },
  {
    id: 72,
    title: "Порыв ярости",
    enTitle: "Burst of Fury",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "Атака наносит удар по двум целям одновременно. Однако сила и дальность снижаются на один. WAY TOO COMPLICATED",
    enDesc: "The attack strikes two targets at once, but its power and range are each reduced by 1. WAY TOO COMPLICATED",
    img: "cards/card_72_poryv_yarosti.png"
  },
  {
    id: 73,
    title: "Хатимаки",
    enTitle: "Hachimaki",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["hpctx"],
    tags: ["toPrint"],
    desc: "Ваша атака берёт любую сложность и наносит на одну рану больше, но вы теряете один жетон жизни.[NL]{На пороге вашей смерти} применить нельзя.",
    enDesc: "Your attack handles any complexity and deals 1 extra wound, but you lose 1 life.[NL]{At death's door} it cannot be played.",
    img: "cards/card_73_povyazka_kamikadze.png"
  },
  {
    id: 74,
    title: "Бросок",
    enTitle: "Throw",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Меняет ваше оружие на метательное с базовой силой атаки 1.",
    enDesc: "Turns your weapon into a thrown weapon with base power 1.",
    img: "cards/card_75_brosok.png"
  },
  {
    id: 75,
    title: "Всей силой",
    enTitle: "Crushing Blow",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Итоговая сила атаки становится равна вашему количеству жетонов жизни.",
    enDesc: "The attack's final power equals your current life.",
    img: "cards/card_74_sokrushitelnyy_udar.png"
  },
  {
    id: 76,
    title: "Кипящий яд",
    enTitle: "Boiling Venom",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Отравленный противник получит на две раны больше.",
    enDesc: "A Poisoned target takes 2 extra wounds.",
    img: "cards/card_76_kipyashchiy_yad.png"
  },
  {
    id: 77,
    title: "Длань сёгуна",
    enTitle: "Shogun's Hand",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы не тратите свою попытку атаки в данном ударе.[NL]{Самураи} наносят дополнительно 1 рану.[NL]{Ниндзя} штрафуются сбросом карты.",
    enDesc: "This strike does not use up your attack.[NL]{Samurai} deal 1 extra wound.[NL]{Ninja} pay the price of a discarded card.",
    img: "cards/card_77_dlan_syoguna.png"
  },
  {
    id: 78,
    title: "Дух сёгуна",
    enTitle: "Shogun's Spirit",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "От вашей атаки невозможно защититься, и ловушки не действуют. (ушло в удар тени)",
    enDesc: "Your attack cannot be defended and Traps have no effect. (merged into Shadow Strike)",
    img: "cards/card_78_dukh_syoguna.png"
  },
  {
    id: 79,
    title: "Насквозь",
    enTitle: "Piercing Strike",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Ваша атака оружием полностью игнорирует все бонусы от стойки, персонажа и эффектов цели.",
    enDesc: "Your weapon attack completely ignores every bonus from the target's Stance, Character and Effects.",
    img: "cards/card_80_pronzitelnyy_udar.png"
  },
  {
    id: 80,
    title: "Критический удар",
    enTitle: "Critical Strike",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Сила атаки увеличивается на 2.",
    enDesc: "+2 attack power.",
    img: "cards/card_79_kriticheskiy_udar.png"
  },
  {
    id: 1081,
    title: "Финальный удар",
    enTitle: "Finishing Blow",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["toPrint"],
    desc: "Финальная сила атаки равна количеству недостающих жетонов жизни цели.",
    enDesc: "The attack's final power equals the target's missing life.",
    img: "cards/card_1081_finalnyi_udar.png"
  },
  {
    id: 1083,
    title: "Кубитори",
    enTitle: "Kubitori",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["toPrint"],
    desc: "+1 к силе атаки. При убийстве врага этой атакой вы можете забрать себе его стойку, ауру и любые эффекты.",
    enDesc: "+1 attack power. If this attack kills the enemy, you may take their Stance, Aura and any Effects for yourself.",
    img: "cards/card_1083_kubitori.png"
  },
  {
    id: 1084,
    title: "Победный удар",
    enTitle: "Victor's Strike",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["toPrint"],
    desc: "Ваше текущее количество жетонов победы добавляется к силе атаки.",
    enDesc: "Add your current victory points to the attack's power.",
    img: "cards/card_1084_pobednyi_udar.png"
  },
  {
    id: 1032,
    title: "Рэнкэй",
    enTitle: "Renkei",
    types: ["modifier", "intervention"],
    qty: 1,
    group: "modifier",
    icons: ["intervention"],
    tags: ["draft", "toPrint"],
    desc: "Сама по себе ничего не делает. Сыграйте на свою атаку: любой союзник может тут же выложить в неё свой модификатор с руки — он действует, как будто сыгран вами.",
    enDesc: "Does nothing by itself. Play it on your attack: any ally may immediately add a Modifier from their hand to it — it works as if you had played it.",
    img: "cards/card_1032_renkei.png"
  },
  // ── ГРУППОВЫЕ ДЕЙСТВИЯ (стр. 12) ─────────────────────────────────
  {
    id: 81,
    title: "Онсэн",
    enTitle: "Onsen",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Полностью восстановите себе здоровье и снимите с себя любые эффекты и яд, остальные активные игроки +1 ХП. -ИЛИ- Все активные игроки +2 ХП и снимают яд.",
    enDesc: "Fully restore your life and clear every Effect and Poison from yourself; each other living player gains 1 life. -OR- Every living player gains 2 life and clears Poison.",
    img: "cards/card_81_celitelnyye_istochniki.png"
  },
  {
    id: 82,
    title: "Миротворцы",
    enTitle: "Peacemakers",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Остальные активные игроки скидывают карту защиты или оружия, либо отдают вам карту из руки на свой выбор.",
    enDesc: "Each other living player discards a Defense or a Weapon, or hands you a card of their choice from their hand.",
    img: "cards/card_82_mirotvortsy.png"
  },
  {
    id: 83,
    title: "Потасовка",
    enTitle: "Brawl",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Все остальные активные игроки теряют свою стойку и сбрасывают свою ловушку.",
    enDesc: "Every other living player loses their Stance and discards their Trap.",
    img: "cards/card_83_potasovka.png"
  },
  {
    id: 84,
    title: "Чайная церемония",
    enTitle: "Tea Ceremony",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Вы берёте 4 карты из колоды, остальные активные игроки берут по 1 карте. -ИЛИ- Все активные игроки берут по 2 карты из колоды.",
    enDesc: "You draw 4 cards and each other living player draws 1. -OR- Every living player draws 2 cards.",
    img: "cards/card_84_chaynaya_tseremoniya.png"
  },
  {
    id: 85,
    title: "Просветление",
    enTitle: "Revelation",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["aoe", "charges"],
    tags: ["toPrint"],
    desc: "Все ловушки, кроме вашей, на столе открываются, но продолжают действовать. За каждую просветлённую ловушку (не более трёх) вы берёте карту из колоды.",
    enDesc: "Every Trap on the table except yours is revealed, but stays in play. Draw a card for each Trap revealed (no more than three).",
    img: "cards/card_85_prosvietlenie.png"
  },
  {
    id: 86,
    title: "Вихрь ярости",
    enTitle: "Whirlwind of Fury",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: ["draft"],
    desc: "Играется в паре с картой неметательного оружия, берущего сложность 2 или выше. Минуя ловушки, активные игроки получают урон от оружия (без бонусов) или скидывают защиту. Тратит атаку. TODO: реворк. Условие «неметательное оружие сложности 2+» после отмены рассадки описывает только пробивное оружие и ничего не говорит о замахе — вариант привязать к классу {Древковое}: вихрь и есть круговой удар древком. Заодно решить, бьёт ли он союзников (сейчас — всех активных).",
    enDesc: "Played together with a non-thrown weapon that handles complexity 2 or higher. Ignoring Traps, every living player takes the weapon's damage (no bonuses) or discards a Defense. Uses up your attack. TODO: rework. Since seating no longer matters, «a non-thrown weapon of complexity 2+» only describes armour-piercing weapons and says nothing about the sweep — consider tying it to the {Polearm} class instead: the whirlwind is a circular polearm strike. Also decide whether it hits allies (currently every living player).",
    img: "cards/card_86_vikhr_yarosti.png"
  },
  {
    id: 87,
    title: "Шквал огня",
    enTitle: "Storm of Fire",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту и за счёт каждой другой карты с руки метните в других метательным оружием силой 1. От этого можно защититься. Максимум 1 удар в одну цель. Тратит атаку. TODO: реворк. Из туду: переделать под shared spare — союзники доплачивают метательным оружием с руки, — либо убрать «тратит атаку».",
    enDesc: "Play this card and spend any other cards from your hand to throw a ranged attack of power 1 at another player for each one. These may be defended. At most 1 hit per target. Uses up your attack. TODO: rework. From the to-do list: turn it into a shared spare — allies chip in thrown weapons from their hands — or drop «uses up your attack».",
    img: "cards/card_shkval_ognya.png"
  },
  {
    id: 88,
    title: "Кислотный взрыв",
    enTitle: "Acid Burst",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["thrust", "poison", "charges"],
    tags: ["poison", "toPrint"],
    desc: "За каждое отравление на столе выбранный вами игрок теряет жетон жизни.[NL]{Под аурой Бочки зловония} можете взорвать её: аура остаётся на столе, а все враги получают отравление.",
    enDesc: "A player of your choice loses 1 life for every Poison on the table.[NL]{Under the Barrel of Stench} you may blow it up: the aura stays in play, and every enemy becomes Poisoned.",
    img: "cards/card_acid_explosion.png"
  },
  {
    id: 89,
    title: "Град стрел",
    enTitle: "Arrow Storm",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: ["trash"],
    desc: "Все ловушки на столе сбрасываются в сброс. (ушло в потасовку)",
    enDesc: "Every Trap on the table goes to the discard pile. (merged into Brawl)",
    img: "cards/card_88_grad_strel.png"
  },
  {
    id: 90,
    title: "Боевой крик",
    enTitle: "War Cry",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: ["thrust"],
    tags: ["toPrint"],
    desc: "Остальные активные игроки скидывают карту защиты или два жетона жизни. TODO: реворк. Открытый вопрос из туду — куда идёт победное очко, если крик добивает; по правилу выпада оно уходит сыгравшему карту, проверить, что это и хотели.",
    enDesc: "Each other living player discards a Defense card or loses 2 life. TODO: rework. Open question from the to-do list — who gets the victory point when the cry finishes a player; under the thrust rule it goes to whoever played the card, confirm that is the intent.",
    img: "cards/card_89_boevoy_krik.png"
  },
  {
    id: 3091,
    title: "Обыск",
    enTitle: "Inspection",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Остальные активные игроки выкладывают перед собой на своё усмотрение любую карту в открытую. Изучив карты, вы можете взять любую из них себе в руку.",
    enDesc: "Each other living player lays out one card of their choice face up. After looking them over, you may take any one of those cards into your hand.",
    img: "cards/card_obisk.png"
  },
  {
    id: 3092,
    title: "?Cбор клана 1?",
    enTitle: "?Clan Gathering 1?",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["charges"],
    tags: ["trash", "draft"],
    desc: "За каждого активного союзника, ваши союзника берут по карте из колоды.",
    enDesc: "For each living ally, your allies each draw a card.",
    img: "cards/card_todo.png"
  },
  {
    id: 3093,
    title: "?Cбор клана 2?",
    enTitle: "?Clan Gathering 2?",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["charges"],
    tags: ["draft", "trash"],
    desc: "За каждого активного союзника, ваши союзника восстанавливают 1 жетон жизни.",
    enDesc: "For each living ally, your allies each restore 1 life.",
    img: "cards/card_todo.png"
  },
  {
    id: 3094,
    title: "Крик возмездия",
    enTitle: "Cry of Vengeance",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["charges"],
    tags: [],
    desc: "Каждый враг получает атаку равную по силе количеству ваших союзников при смерти. От этого нельзя защититься.",
    enDesc: "Every enemy takes an attack with power equal to the number of your allies at death's door. This cannot be defended.",
    img: "cards/card_redemption_cry.png"
  },
  {
    id: 1094,
    title: "Эстафета мечей",
    enTitle: "Relay of Blades",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Каждый активный игрок выбирает 1 карту со своей руки и кладёт её закрытой перед собой. Когда все выложили — карты сдвигаются на одну позицию по часовой стрелке (каждый получает закрытую карту соседа справа).",
    enDesc: "Every living player picks 1 card from their hand and places it face down in front of them. Once all are down, the cards shift one seat clockwise (each player takes the face-down card of the neighbour on their right).",
    img: "cards/card_wave.png"
  },
  {
    id: 1137,
    title: "Военный совет",
    enTitle: "War Council",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: ["toPrint"],
    desc: "Все живые союзники выкладывают одну карту в открытую перед собой, вы выбираете какой из союзников получит какую. Нельзя остаться при своей карте.",
    enDesc: "Every living ally lays out one card face up in front of them, and you decide which ally gets which. No one may keep their own card.",
    img: "cards/card_forum.png"
  },
  {
    id: 1138,
    title: "Кровное родство",
    enTitle: "Blood Kin",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "На ваше усмотрение вы перераспределяете жетоны жизни между живыми союзниками.",
    enDesc: "Redistribute life among your living allies however you see fit.",
    img: "cards/card_blood_bound.png"
  },
  {
    id: 1139,
    title: "Плечом к плечу",
    enTitle: "Side by Side",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["thrust", "charges"],
    tags: ["toPrint"],
    desc: "Вы наносите 1 рану.[NL]Каждый союзник может сыграть карту оружия как вмешательство, добавив ещё 1 рану — не более одной карты с игрока.",
    enDesc: "You deal 1 wound.[NL]Each ally may play a weapon card as an Intervention to add 1 more wound - at most one card per player.",
    img: "cards/card_shoulder_to_shoulder.png"
  },
  // ── ЭФФЕКТЫ постоянные/разовые (стр. 13–14) ──────────────────────
  {
    id: 91,
    title: "Метка убийцы",
    enTitle: "Killer's Mark",
    types: ["effect"],
    qty: 4,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Все атаки по вам наносят на одну рану больше, и атакующий берёт 1 карту из колоды.[NL]{Убивший вас игрок} берёт две карты из колоды.",
    enDesc: "Every attack against you deals 1 extra wound, and the attacker draws a card.[NL]{The player who kills you} draws two cards.",
    img: "cards/card_90_metka_ubiytsy.png"
  },
  {
    id: 92,
    title: "Противоядие",
    enTitle: "Antidote",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Вас нельзя отравить ядом. Текущее отравление снимается.",
    enDesc: "You cannot be Poisoned. Any Poison on you is cleared.",
    img: "cards/card_91_protivoyadie.png"
  },
  {
    id: 93,
    title: "Укус змеи",
    enTitle: "Snakebite",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: ["toPrint"],
    desc: "Каждое лечение по игроку снижается на единицу. Также все негативные эффекты от отравления удваиваются. Пока вы отравлены, вы не можете пользоваться бонусами стойки.[NL]На {Минамото} не действует.",
    enDesc: "Every point of healing on this player is reduced by 1, and every penalty from Poison is doubled. While you are Poisoned, you cannot use Stance bonuses.[NL]Has no effect on {Minamoto}.",
    img: "cards/card_92_ukus_zmeyi.png"
  },
  {
    id: 94,
    title: "Кагинава",
    enTitle: "Kaginawa",
    types: ["effect"],
    qty: 3,
    group: "effect",
    icons: [],
    tags: ["toPrint"],
    desc: "Сложность атак по вам всегда равна 1 — Доспех и другие повышения сложности не спасают.",
    enDesc: "Attacks against you are always complexity 1 — Armor and other complexity increases do not help.",
    img: "cards/card_93_kaginava.png"
  },
  {
    id: 95,
    title: "Разоружение",
    enTitle: "Disarm",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Выбранный игрок не может производить прямые атаки оружием.[NL]{Самураи} чтобы атаковать вас должны сбросить 1 карту.",
    enDesc: "The chosen player cannot make direct weapon attacks.[NL]{Samurai} must discard a card to attack you.",
    img: "cards/card_94_razoruzhenie.png"
  },
  {
    id: 96,
    title: "Завеса дыма",
    enTitle: "Smoke Screen",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: ["trash"],
    desc: "TODO: Следующий игровой ход выбранный игрок будто при смерти. ЧТО-ТО сделать с этой картой! Может в стойку из вмешательства?",
    enDesc: "TODO: For the next turn the chosen player counts as being at death's door. DO SOMETHING with this card! Maybe move it from Intervention into a Stance?",
    img: "cards/card_95_zavesa_dyma.png"
  },
  {
    id: 97,
    title: "Пыль в глаза",
    enTitle: "Dust in the Eyes",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: ["toPrint"],
    desc: "Ваши атаки могут брать только сложность 1, и вы не можете использовать метательное оружие.",
    enDesc: "Your attacks may only take complexity 1, and you cannot use thrown weapons.",
    img: "cards/card_97_pyl_v_glaza.png"
  },
  {
    id: 99,
    title: "Чаша благовоний",
    enTitle: "Incense Bowl",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: ["charges"],
    tags: ["toPrint"],
    desc: "Выбранный игрок скидывает указанный вами эффект. За каждую дополнительно сброшенную карту можно скинуть ещё 1 эффект. За каждый такой скинутый эффект, вы восстанавливаете 1 жетон жизни любому игроку.",
    enDesc: "The chosen player discards an Effect you name. For each extra card discarded, one more Effect may be removed. For every Effect removed this way, restore 1 life to any player.",
    img: "cards/card_98_chasha_blagovoniy.png"
  },
  {
    id: 100,
    title: "Слабость",
    enTitle: "Weakness",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: ["toPrint"],
    desc: "Ваши атаки не могут нанести больше одной раны.",
    enDesc: "Your attacks cannot deal more than one wound.",
    img: "cards/card_99_slabost.png"
  },
  {
    id: 101,
    title: "Беззащитность",
    enTitle: "Defenseless",
    types: ["effect"],
    qty: 2,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Игрок не может защищаться от атак.",
    enDesc: "This player cannot defend against attacks.",
    img: "cards/card_100_bezzashchitnost.png"
  },
  {
    id: 102,
    title: "Дух лидера",
    enTitle: "Leader's Spirit",
    types: ["effect"],
    qty: 2,
    group: "effect",
    icons: [],
    tags: ["trash", "draft"],
    desc: "Выбранный игрок берёт на одну карту больше в фазе набора. TODO: remove?",
    enDesc: "The chosen player draws one extra card in the draw phase. TODO: remove?",
    img: "cards/card_101_dukh_lidera.png"
  },
  {
    id: 103,
    title: "Бессилие",
    enTitle: "Exhaustion",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "За ход вы можете сделать на одну прямую атаку меньше.",
    enDesc: "You may make one fewer direct attack per turn.",
    img: "cards/card_102_bessilie.png"
  },
  {
    id: 104,
    title: "Эгида",
    enTitle: "Aegis",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: ["trash"],
    desc: "Выбранный игрок автоматически защищается от атаки. Новая механика игра и так позволяет многим помонать зашищаться.",
    enDesc: "The chosen player automatically defends against an attack. New mechanic — the game already lets plenty of players help with defending.",
    img: "cards/card_103_egida.png"
  },
  {
    id: 4104,
    title: "Проклятье",
    enTitle: "Curse",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Получая любой вид урона, вы получаете на 2 раны больше. Проклятье переходит на убившего вас игрока.",
    enDesc: "You take 2 extra wounds from any kind of damage. The Curse passes to the player who kills you.",
    img: "cards/card_curse.png"
  },
  {
    id: 5104,
    title: "Доспех",
    enTitle: "Armor",
    types: ["effect"],
    qty: 2,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Сложность атак по вам увеличивается на 1.",
    enDesc: "Attacks against you are 1 harder.",
    img: "cards/card_armor.png"
  },

  // ── ДЕЙСТВИЯ (стр. 15–16) ─────────────────────────────────────────
  {
    id: 105,
    title: "Васаби",
    enTitle: "Wasabi",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: [],
    tags: [],
    desc: "Выбранный игрок избавляется от яда, получает жетон жизни и берёт одну карту из колоды.",
    enDesc: "The chosen player is cured of Poison, restores 1 life and draws a card.",
    img: "cards/card_104_vasabi.png"
  },
  {
    id: 106,
    title: "Зов предков",
    enTitle: "Ancestral Call",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Поменяйте эту карту на любую из сброса не глубже последних 10, но не ранее последних 3. TODO: добор из сброса запрещён (мета-правило №7) — переделать на обмен с рукой другого игрока.",
    enDesc: "Swap this card for any card among the last 10 in the discard pile, but not among the last 3. TODO: drawing from the discard pile is banned (meta-rule 7) — rework into a swap with another player.",
    img: "cards/card_105_zov_predkov.png"
  },
  {
    id: 107,
    title: "Швы",
    enTitle: "Stitches",
    types: ["action"],
    qty: 4,
    group: "action",
    icons: ["hpctx"],
    tags: [],
    desc: "Любой выбранный активный игрок восстанавливает 2 жетона жизни. В стойке {капеллана} восстанавливает на 1 жизнь больше.[NL]{На пороге вашей смерти} вы можете вылечить другого игрока на 3 жизни.",
    enDesc: "Any living player of your choice restores 2 life. In the {Chaplain} stance, restore 1 life more.[NL]{At death's door} you may heal another player for 3 life.",
    img: "cards/card_106_shvy.png"
  },
  {
    id: 108,
    title: "Сэппуку",
    enTitle: "Seppuku",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы выкладываете все карты перед собой в открытую, ваши активные союзники могут забрать любые ваши карты себе, не превышая ограничение в 8 карт, остальное идёт в сброс. Потом вы умираете и победное очко другому игроку. Таким образом нельзя потерять последнее победное очко.[NL]{Ниндзя} не могут совершать Сэппуку.",
    enDesc: "Lay all your cards face up in front of you. Your living allies may take any of them, up to the limit of 8 cards; the rest go to the discard pile. You then die and another player scores a victory point. You cannot lose your last victory point this way.[NL]{Ninja} cannot commit Seppuku.",
    img: "cards/card_107_seppuku.png"
  },
  {
    id: 109,
    title: "Саке",
    enTitle: "Sake",
    types: ["action"],
    qty: 4,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сбросьте эту карту, чтобы взять 1 новую из колоды. Далее за каждую сброшенную карту (не более двух) берите дополнительно 1 карту из колоды. {Союзники} могут вам помочь в доборе, сбрасывая свои карты, но не более двух каждый.",
    enDesc: "Discard this card to draw 1 new card. Then draw 1 more card for each card you discard (no more than two). {Allies} may help you draw by discarding cards of their own, but no more than two each.",
    img: "cards/card_108_sake.png"
  },
  {
    id: 110,
    title: "Боевой банан",
    enTitle: "Battle Banana",
    types: ["action"],
    qty: 2,
    group: "action",
    icons: [],
    tags: ["draft", "trash"],
    desc: "Другой выбранный активный игрок скидывает свою текущую стойку, за это вы берёте карту. Или можете сбросить эту карту, чтобы взять две новых из колоды. TODO: remove carD entirelly? Or make something else based on having a condition of having STAANCE?",
    enDesc: "Another living player of your choice discards their current Stance, and you draw a card for it. Or discard this card to draw two new ones. TODO: remove carD entirelly? Or make something else based on having a condition of having STAANCE?",
    img: "cards/card_46_boevoy_banan.png"
  },
  {
    id: 111,
    title: "Предательство",
    enTitle: "Betrayal",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы сбрасываете победное очко в сброс (если не последнее), и за это получаете семь карт из колоды. Не считается смертью.[NL]{Самураи} не могут предавать.",
    enDesc: "Discard a victory point (unless it is your last) and draw seven cards for it. This does not count as death.[NL]{Samurai} cannot betray.",
    img: "cards/card_110_predatelstvo.png"
  },
  {
    id: 112,
    title: "Сапёр",
    enTitle: "Sapper",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: ["charctx"],
    tags: ["toPrint"],
    desc: "Обезвредьте любую ловушку на столе; {Иё} вместо этого может забрать её себе в руку.[NL]Либо скиньте две карты с одинаковым названием, чтобы взять две новых из колоды; отравленное и обычное оружие считаются одинаковыми.",
    enDesc: "Disarm any Trap on the table; {Iyo} may take it into her hand instead.[NL]Or discard two cards with the same name to draw two new ones; a poisoned and a plain version of a weapon count as the same.",
    img: "cards/card_111_sapyor.png"
  },
  {
    id: 113,
    title: "Эквилибриум",
    enTitle: "Equilibrium",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Количество жетонов жизни выбранного игрока становится равно вашему.[NL]{Ниндзя} должен сбросить одну карту для совершения действия.",
    enDesc: "The chosen player's life becomes equal to yours.[NL]A {Ninja} must discard a card to take this action.",
    img: "cards/card_112_ekvilibrium.png"
  },
  {
    id: 114,
    title: "Передышка",
    enTitle: "Respite",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: ["hpctx"],
    tags: [],
    desc: "Восстановите все недостающие жетоны жизни. Любой другой игрок на ваш выбор берёт одну карту из колоды.[NL]{При полном здоровье} вместо одной карты — две, и можете взять карты себе.",
    enDesc: "Restore all your missing life. Any other player of your choice draws a card.[NL]{At full health} they draw two instead, and you may keep the cards yourself.",
    img: "cards/card_113_peredyshka.png"
  },
  {
    id: 115,
    title: "Ясновидение",
    enTitle: "Clairvoyance",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Выбранный игрок показывает всем свои карты с руки до следующего действия.[NL]{Ниндзя} может забрать любую из карт себе.",
    enDesc: "The chosen player reveals their hand to everyone until the next action.[NL]A {Ninja} may take any one of those cards.",
    img: "cards/card_114_yasnovidenie.png"
  },
  {
    id: 116,
    title: "Яд фугу",
    enTitle: "Fugu Poison",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["poison", "charctx"],
    tags: ["poison", "toPrint"],
    desc: "Отравляет выбранного активного игрока; {Минамото} может отравить и себя. Отравленная этой картой Минамото берёт две карты из колоды.",
    enDesc: "Poisons the chosen living player; {Minamoto} may poison herself. If Minamoto is poisoned by this card, she draws two cards.",
    img: "cards/card_116_yad_fugu.png"
  },
  {
    id: 117,
    title: "Обмен душ",
    enTitle: "Soul Swap",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы меняетесь с выбранным игроком количеством жетонов жизни.[NL]{Самурай} должен сбросить одну карту для совершения действия.",
    enDesc: "You and the chosen player swap life totals.[NL]A {Samurai} must discard a card to take this action.",
    img: "cards/card_115_obmen_dush.png"
  },
  {
    id: 118,
    title: "Магатама",
    enTitle: "Magatama",
    types: ["action"],
    qty: 2,
    group: "action",
    icons: [],
    tags: [],
    desc: "Либо сыграйте эту карту, чтобы взять 4 новых из колоды, либо оставьте, чтобы получить победное очко.",
    enDesc: "Either play this card to draw four new cards, or keep it to score a victory point.",
    img: "cards/card_117_dayme.png"
  },
  {
    id: 119,
    title: "Переливание крови",
    enTitle: "Blood Transfusion",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: [],
    tags: ["trash"],
    desc: "Очищает любого игрока от отравления и передаёт его любому другому. UPD: перешло в куклу вуду",
    enDesc: "Cures any player of Poison and passes it to any other. UPD: merged into the Voodoo Doll",
    img: "cards/card_118_perelivanie_krovi.png"
  },
  {
    id: 120,
    title: "Жертва крови",
    enTitle: "Blood Sacrifice",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["charctx"],
    tags: ["toPrint"],
    desc: "Сыграв эту карту, берите за каждый сброшенный жетон жизни (кроме последнего, не более трёх) новую карту из колоды. {Усивака} может сыграть её в любой момент, даже в чужой ход.",
    enDesc: "Play this card and draw a new card for every life you spend (never your last, no more than three). {Ushiwaka} may play it at any moment, even on another player's turn.",
    img: "cards/card_119_zhertva_krovi.png"
  },
  {
    id: 1121,
    title: "Кампо",
    enTitle: "Kampo",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["toPrint"],
    desc: "Сыграв эту карту, можете сбросить любое необходимое количество карт, восстановив за каждую 1 жизнь.",
    enDesc: "Play this card and discard as many cards as you need, restoring 1 life for each.",
    img: "cards/card_kampo.png"
  },
  {
    id: 1122,
    title: "Смертные муки",
    enTitle: "Death Throes",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сыграв эту карту, возьмите по 1 карте из колоды за каждый недостающий жетон жизни (не более трёх).[NL]{Если вы отравлены}, возьмите дополнительно 1 карту ко всему добору.",
    enDesc: "Play this card and draw 1 card for every point of life you are missing.[NL]{If you are Poisoned}, draw 1 more card on top of that.",
    img: "cards/card_smertnie_muki.png"
  },
  {
    id: 31121,
    title: "Горячая картошка",
    enTitle: "Burning Coal",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "В открытую передайте эту карту любому активному игроку, взамен он обязан вам дать одну карту по своему желанию в закрытую. Эту карту нельзя положить в сброс, только обратно в колоду сверху.",
    enDesc: "Pass this card face up to any living player; in exchange they must give you one card of their choice, face down. This card cannot go to the discard pile — only back on top of the deck.",
    img: "cards/card_hot_potato.png"
  },
  {
    id: 101122,
    title: "Мародёр",
    enTitle: "Looter",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["toPrint"],
    desc: "Выбранный игрок выкладывает все карты с руки в открытую. Вы и каждый ваш {союзник} забираете по одной из них себе.",
    enDesc: "The chosen player lays their whole hand face up. You and each of your {allies} take one of those cards.",
    img: "cards/card_loot_corpse.png"
  },
  {
    id: 1123,
    title: "Зеркало души",
    enTitle: "Soul Mirror",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы вызвать действия, совершаемые персонажем любого игрока {после смерти}, как будто он ваш союзник.",
    enDesc: "Play this card to trigger the abilities any player's Character performs {after death}, as if they were your ally.",
    img: "cards/card_soul_mirror.png"
  },
  {
    id: 1124,
    title: "Лазутчик",
    enTitle: "Infiltrator",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы забираете себе ауру выбранного активного игрока.",
    enDesc: "You take the Aura of the chosen living player for yourself.",
    img: "cards/card_spy.png"
  },
  // ── ВМЕШАТЕЛЬСТВА (стр. 17) ───────────────────────────────────────
  {
    id: 1125,
    title: "Эстафета",
    enTitle: "Relay",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Вы можете передать свою ауру союзнику, или по согласию забрать себе его ауру.",
    enDesc: "You may pass your Aura to an ally, or take theirs with their consent.",
    img: "cards/card_baton.png"
  },
  {
    id: 121,
    title: "Исцеление",
    enTitle: "Mending",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: ["toPrint"],
    desc: "Восстановите все жетоны жизни отравленному ядом игроку и снимите само отравление.",
    enDesc: "Restore all life to a Poisoned player and clear the Poison itself.",
    img: "cards/card_120_istselenie.png"
  },
  {
    id: 122,
    title: "Смерть от фугу",
    enTitle: "Death by Fugu",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["thrust"],
    tags: ["toPrint"],
    desc: "Сыграйте эту карту, чтобы нанести две раны отравленному ядом игроку.",
    enDesc: "Play this card to deal two wounds to a Poisoned player.",
    img: "cards/card_121_smert_ot_fugu.png"
  },
  {
    id: 123,
    title: "Имбирь",
    enTitle: "Ginger",
    types: ["intervention"],
    qty: 2,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы восстановить любому игроку один жетон жизни.",
    enDesc: "Play this card to restore one life to any player.",
    img: "cards/card_122_imbir.png"
  },
  {
    id: 124,
    title: "Удар дракона",
    enTitle: "Dragon Strike",
    types: ["intervention"],
    qty: 2,
    group: "intervention",
    icons: ["thrust"],
    tags: ["toPrint"],
    desc: "Сыграйте эту карту, чтобы нанести одну рану любому выбранному игроку.",
    enDesc: "Play this card to deal one wound to any player of your choice.",
    img: "cards/card_123_udar_drakona.png"
  },
  {
    id: 125,
    title: "Подвиг",
    enTitle: "Feat of Valor",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["hpctx", "rolectx"],
    tags: [],
    desc: "Сыграйте эту карту, чтобы перенаправить прямую атаку оружия на себя.[NL]{На пороге вашей смерти} ваши союзники берут по 1 карте из колоды.[NL]{Самураи} при этом получают на одну рану меньше.",
    enDesc: "Play this card to take a direct weapon attack onto yourself.[NL]{At death's door} your allies each draw a card.[NL]{Samurai} take one wound less doing so.",
    img: "cards/card_124_podvig.png"
  },
  {
    id: 126,
    title: "Рука помощи",
    enTitle: "Helping Hand",
    types: ["intervention"],
    qty: 4,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы любой игрок вашей команды передал в закрытую любую карту из своей руки другому игроку команды — карту и получателя он выбирает сам.",
    enDesc: "Play this card to let any player on your team pass a card from their hand, face down, to another player on the team — they choose both the card and the recipient.",
    img: "cards/card_125_ruka_pomoshchi.png"
  },
  {
    id: 127,
    title: "Весточка",
    enTitle: "Message",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: ["trash"],
    desc: "Сыграйте эту карту, чтобы передать любому игроку в закрытую любую другую карту из своей руки. (ушло в руку помощи)",
    enDesc: "Play this card to pass any other card from your hand to any player, face down. (merged into Helping Hand)",
    img: "cards/card_126_vestochka.png"
  },
  {
    id: 128,
    title: "Симулянт",
    enTitle: "Feigned Death",
    types: ["intervention", "effect"],
    qty: 3,
    group: "intervention",
    icons: ["effect8"],
    tags: ["toPrint"],
    desc: "Выбранный игрок с его согласия притворяется мёртвым до конца текущего хода: у него остаётся 1 жетон жизни, его аура не действует.",
    enDesc: "The chosen player, with their consent, plays dead until the end of the current turn: they keep 1 life, and their Aura does not work.",
    img: "cards/card_127_simulyant.png"
  },
  {
    id: 1029,
    title: "Осколки",
    enTitle: "Shattered Steel",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Уничтожает сыгранное оружие на столе, карта идёт в сброс, а атака отменяется, не тратя попытку.",
    enDesc: "Destroys a weapon played on the table: the card goes to the discard pile and the attack is cancelled without using up the attempt.",
    img: "cards/card_shards.png"
  },
  {
    id: 1030,
    title: "Сон Ёкая",
    enTitle: "Yokai's Slumber",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Следующее действие выбранного игрока завершит его ход. Сюда не входит скидывание парных карт.",
    enDesc: "The chosen player's next action ends their turn. Discarding paired cards does not count.",
    img: "cards/card_dream_of_ekai.png"
  },
  {
    id: 1031,
    title: "Щитолом",
    enTitle: "Shieldbreaker",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: ["toPrint"],
    desc: "Сыграйте в ответ на карту защиты: она уничтожается, атака проходит как без защиты.",
    enDesc: "Play in response to a Defense card: it is destroyed and the attack resolves as if undefended.",
    img: "cards/card_1031_shchitolom.png"
  },

  // ── ПРОЧИЕ ДЕЙСТВИЯ (стр. 18) ─────────────────────────────────────
  {
    id: 129,
    title: "Воровство",
    enTitle: "Sleight of Hand",
    types: ["action"],
    qty: 2,
    group: "action",
    icons: ["charctx"],
    tags: ["toPrint"],
    desc: "Заберите одну случайную карту с руки любого активного игрока. {Така} забирает две.",
    enDesc: "Take one random card from the hand of any living player. {Taka} takes two.",
    img: "cards/card_128_vorovstvo.png"
  },
  {
    id: 130,
    title: "Кукла вуду",
    enTitle: "Voodoo Doll",
    types: ["action"],
    qty: 4,
    group: "action",
    icons: [],
    tags: [],
    desc: "Можете выбрать отравление или любой эффект на столе и переложить его на любого игрока.",
    enDesc: "Choose a Poison or any Effect on the table and move it onto any player.",
    img: "cards/card_129_kukla_vudu.png"
  },
  {
    id: 131,
    title: "Дурман",
    enTitle: "Datura",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["trash"],
    desc: "Вы забираете выбранный эффект игрока на себя. UPD: ушло в куклу вуду",
    enDesc: "You take a chosen Effect off a player and onto yourself. UPD: merged into the Voodoo Doll",
    img: "cards/card_130_durman.png"
  },
  {
    id: 132,
    title: "Кэцу нуги",
    enTitle: "Ketsu Nugi",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Забираете у игрока жетон жизни и добавляете его себе.[NL]{Если вы отравлены}, то передаёте игроку отравление.",
    enDesc: "Take one life from a player and add it to your own.[NL]{If you are Poisoned}, you pass the Poison to that player instead.",
    img: "cards/card_131_sifon_zhizni.png"
  },
  {
    id: 133,
    title: "Перехват",
    enTitle: "Intercept",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["trash"],
    desc: "TODO: нужна ли карта с переделой Сапёра? Вы забираете ловушку другого игрока себе в руку. UPD: Into sapper",
    enDesc: "TODO: is this card needed once Sapper is reworked? You take another player's Trap into your hand. UPD: Into sapper",
    img: "cards/card_132_obman.png"
  },
  {
    id: 1133,
    title: "Камикадзе",
    enTitle: "Kamikaze",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["toPrint"],
    desc: "Вы и согласный живой {союзник} сбрасываете все свои карты — с руки и со стола, — и вы убиваете выбранного врага.",
    enDesc: "You and a willing living {ally} discard all your cards — hand and table — and you kill the chosen enemy.",
    img: "cards/card_kamikadze.png"
  },
  {
    id: 1134,
    title: "Ва банк",
    enTitle: "All In",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы меняетесь полностью картами в руке в закрытую с выбранным активным игроком.",
    enDesc: "You swap your entire hand, face down, with the chosen living player.",
    img: "cards/card_va_bank.png"
  },
  {
    id: 1135,
    title: "Ёкай",
    enTitle: "Yokai",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["toPrint"],
    desc: "Заберите любую чужую карту со стола — открытую или закрытую — себе в руку.",
    enDesc: "Take any other player's card from the table — face up or face down — into your hand.",
    img: "cards/card_ekai.png"
  },
  {
    id: 1136,
    title: "Укол вслепую",
    enTitle: "Blind Strike",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "У выбранного игрока текущее и недостающее количество жетонов жизни меняются местами.",
    enDesc: "The chosen player's current and missing life swap places.",
    img: "cards/card_motusa.png"
  },
  // ── ПЕРСОНАЖИ (стр. 19) ───────────────────────────────────────────
  {
    id: 135,
    title: "Усивака",
    enTitle: "Ushiwaka",
    subtitle: "Безрассудный налётчик",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "За каждую полученную рану берите карту. «На пороге смерти» для вас — уже при 2 жетонах.[NL]{После вашей смерти} враги получают 1 рану.",
    enDesc: "Draw a card for every wound you take. For you, “at death's door” starts at 2 life.[NL]{After your death} enemies take 1 wound.",
    img: "cards/card_135_usivaka.png"
  },
  {
    id: 136,
    title: "Таранага",
    enTitle: "Taranaga",
    subtitle: "Искусный стратег",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "В фазе набора берите на 1 карту больше. Лишние карты перед ходом не сбрасывайте, а раздайте союзникам по одной в закрытую. При воровстве, ошеломлении и групповых действиях отдаёте любую карту на свой выбор. Ауру можете выложить перед любым игроком.[NL]{После вашей смерти} передайте свою ауру живому союзнику.",
    enDesc: "Draw 1 extra card in the draw phase. Before your turn, hand cards over the limit to allies, one each, face down, instead of discarding. When robbed, stunned or hit by a group action, you give any card of your choice. You may play an Aura in front of any player.[NL]{After your death} pass your Aura to a living ally.",
    img: "cards/card_136_taranaga.png"
  },
  {
    id: 137,
    title: "Сайго",
    enTitle: "Saigo",
    subtitle: "Последний самурай",
    hp: 6,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Стойку любого умершего можете забрать себе в руку. Рукопашная бьёт на 2. В фазе набора +1 карта за каждую стойку на столе (до 3).[NL]{После вашей смерти} ваша стойка остаётся, а враги возвращают свои в руку.",
    enDesc: "You may take any dead player's Stance into your hand. Bare-handed attacks deal 2. In the draw phase, +1 card per Stance on the table (up to 3).[NL]{After your death} your Stance stays, and enemies return theirs to hand.",
    img: "cards/card_138_kokoro.png"
  },
  {
    id: 138,
    title: "Хандзо",
    enTitle: "Hanzo",
    subtitle: "Неуловимый синоби",
    hp: 4,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Можете защищаться от прямых атак оружием, получая 1 рану. Можете сбросить карту защиты и взять 2 из колоды.",
    enDesc: "You may block direct attacks with a weapon, taking 1 wound. You may discard a Defense to draw 2.",
    img: "cards/card_139_handzo.png"
  },

  {
    id: 142,
    title: "Норио",
    enTitle: "Norio",
    subtitle: "Мирный монах",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Вместо попытки атаки берите 2 карты или верните 1 жетон жизни любому игроку. {Древковое} оружие можете сыграть как карту защиты или вмешательства — за себя или за любого игрока.[NL]{После вашей смерти} каждый союзник может снять с себя один эффект.",
    enDesc: "Instead of an attack attempt, draw 2 cards or restore 1 life to any player. You may play any {Polearm} as a Defense or an Intervention — for yourself or anyone.[NL]{After your death} each ally may remove one Effect from themselves.",
    img: "cards/card_142_norio.png"
  },
  {
    id: 139,
    title: "Иё",
    enTitle: "Iyo",
    subtitle: "Знаток ловушек",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Раз в ход можете передвинуть свою ловушку к союзнику без ловушки или поменять местами две любые на столе, не открывая. Ваша ловушка срабатывает и от метательных атак. В фазе набора +1 карта за каждую ловушку на столе (до 3).[NL]{После вашей смерти} ловушки врагов просвещаются.",
    enDesc: "Once per turn, move your Trap to an ally without one, or swap any two Traps on the table unseen. Your Trap is triggered by thrown attacks too. In the draw phase, +1 card per Trap on the table (up to 3).[NL]{After your death} enemy Traps are revealed.",
    img: "cards/card_140_iyo.png"
  },
  {
    id: 140,
    title: "Така",
    enTitle: "Taka",
    subtitle: "Ловкая воровка",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Раз в ход можете забрать у игрока карту на его выбор или отдать ему свою. Раз в ход можете сбросить 2 карты и взять 3.[NL]{После вашей смерти} можете отдать каждому союзнику по карте в закрытую.",
    enDesc: "Once per turn, take a card of a player's choice from them, or give them one of yours. Once per turn, discard 2 cards to draw 3.[NL]{After your death} you may give each ally a card face down.",
    img: "cards/card_141_taka.png"
  },
  {
    id: 145,
    title: "Манасэ",
    enTitle: "Manase",
    subtitle: "Врач Сэнгоку",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Ваше лечение поднимает любого на 1 жетон выше лимита жизней; для карт и пометок лимит прежний. Когда кто-то в вашей команде лечится, берите карту — сколько бы жетонов ни вернулось.[NL]{После вашей смерти} каждый союзник восстанавливает 1 жетон и исцеляется от яда.",
    enDesc: "Your healing may raise anyone 1 life above their life limit; for cards and markers the limit is unchanged. Whenever a teammate heals, draw a card — however much was restored.[NL]{After your death} every ally restores 1 life and is cured of poison.",
    img: "cards/card_145_manase.png"
  },
  {
    id: 146,
    title: "Минамото",
    enTitle: "Minamoto",
    subtitle: "Дух оспы Идзу",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Яд не отнимает у вас жизни, а очко умершего от яда достаётся вам, а не сбросу. {Если вы отравлены}: атаки отравлены, 3 попытки атаки за ход, ранивший вас прямой атакой отравляется. В фазе набора +1 карта за каждого отравленного (до 3).[NL]{После вашей смерти} все враги отравляются.",
    enDesc: "Poison costs you no life, and the point of anyone who dies of poison goes to you, not the discard. {If you are poisoned}: your attacks are poisoned, you have 3 attack attempts, and whoever wounds you with a direct attack is poisoned. In the draw phase, +1 card per poisoned player (up to 3).[NL]{After your death} every enemy is poisoned.",
    img: "cards/card_minamoto.png"
  },

  // ── КОМАНДНЫЕ КАРТЫ (Team Aura / Enemy Objective) ────────────────
  // Выкладываются перед одним игроком (носителем), действуют как «знамя» на всю
  // его команду. Лимит — одна командная карта на команду одновременно. Носитель
  // становится приоритетной целью противника. См. mechanics/new-mechanics-ideas.md
  // №6 и mechanics/team_cards_ideas.html.
  {
    id: 1200,
    title: "Знамя лидера",
    enTitle: "Leader's Banner",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: [],
    desc: "Все атаки {союзников} наносят +1 рану.",
    enDesc: "All attacks by {allies} deal +1 wound.",
    img: "cards/card_leader.png"
  },
  {
    id: 1201,
    title: "Закрытый тыл",
    enTitle: "Covered Flank",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: [],
    desc: "Все {союзники} получают на одну рану меньше от любой прямой атаки (не менее 1).",
    enDesc: "All {allies} take one wound less from any direct attack (never below 1).",
    img: "cards/card_rare.png"
  },
  {
    id: 1202,
    title: "Ровный строй",
    enTitle: "Closed Ranks",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: [],
    desc: "Сложность атак по вашей команде увеличивается на 1.",
    enDesc: "Attacks against your team are 1 harder.",
    img: "cards/card_march.png"
  },
  {
    id: 1203,
    title: "Бочка зловония",
    enTitle: "Barrel of Stench",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Все прямые атаки {союзников} оружием автоматически отравлены, как будто использовалось ядовитое оружие.[NL]{Носитель} получает отравление ядом.",
    enDesc: "All direct weapon attacks by {allies} are automatically Poisoned, as if a poisoned weapon had been used.[NL]The {Bearer} becomes Poisoned.",
    img: "cards/card_87_bochka_zlovoniya.png"
  },
  {
    id: 1204,
    title: "Спина к спине",
    enTitle: "Back to Back",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: [],
    desc: "Любой {союзник} может разыграть карту защиты с руки как вмешательство в защиту другого союзника. Бонусы карты защиты при этом не сохраняются.",
    enDesc: "Any {ally} may play a Defense card from hand as an Intervention to defend another ally. The Defense card's own bonuses do not carry over.",
    img: "cards/card_back_to_back.png"
  },
  {
    id: 1205,
    title: "Стратег",
    enTitle: "Strategist",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: [],
    desc: "В фазе набора каждый {союзник} берёт +1 карту из колоды.",
    enDesc: "In the draw phase each {ally} takes +1 card from the deck.",
    img: "cards/card_camp.png"
  },
  {
    id: 1206,
    title: "Дымовая завеса",
    enTitle: "Smoke Veil",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "{Враги} не могут проводить метательные атаки.",
    enDesc: "{Enemies} cannot make ranged attacks.",
    img: "cards/card_1206_dymovaya_zavesa.png"
  },
  {
    id: 1207,
    title: "Присяга",
    enTitle: "Oath",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: [],
    desc: "Любой живой {союзник} может по согласию принять прямую атаку оружия по другому союзнику на себя (как Подвиг), но получает на 1 рану больше.",
    enDesc: "Any living {ally} may consent to take a direct weapon attack aimed at another ally onto themselves (as with Feat of Valor), but takes one wound more.",
    img: "cards/card_war_duty.png"
  },
  {
    id: 1208,
    title: "Полевая медицина",
    enTitle: "Field Medicine",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Любое лечение {союзников} восстанавливает на 1 жетон жизни больше. Обмен, выравнивание и перенос жетонов лечением не считаются.",
    enDesc: "Any healing of {allies} restores 1 extra life. Swapping, equalising or moving life does not count as healing.",
    img: "cards/card_hospital.png"
  },
  {
    id: 1209,
    title: "Часовой",
    enTitle: "Sentry",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "{Враги} после нанесения ран прямой атакой по вашим союзникам получают от носителя ауры 1 рану, а если носитель в стойке {лучника} — 2.[NL]{Носитель} не может пользоваться метательным оружием.",
    enDesc: "{Enemies} who wound your allies with a direct attack take 1 wound from the Aura's bearer, or 2 if the bearer is in the {Archer} stance.[NL]The {Bearer} cannot use thrown weapons.",
    img: "cards/card_warden.png"
  },
  {
    id: 1210,
    title: "Арсенал",
    enTitle: "Armory",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: [],
    desc: "При совершении прямой атаки оружием (до действий защищающегося), любой {союзник} может с согласия атакующего выставить оружие (как вмешательство), а его забрать себе.",
    enDesc: "When a direct weapon attack is made (before the defender acts), any {ally} may, with the attacker's consent, put a weapon into play as an Intervention and take the attacker's weapon for themselves.",
    img: "cards/card_arsenal.png"
  },

  {
    id: 1211,
    title: "Подпольная сеть",
    enTitle: "Shadow Network",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Раз в свой ход любой {союзник} может обменяться с соратником в закрытую по согласию картами.",
    enDesc: "Once per turn any {ally} may swap cards face down with a comrade, by mutual consent.",
    img: "cards/card_discreete_deal.png"
  },
];
