// Допустимые типы: role | weapon | trap | character | modifier | defense | stance | effect | intervention | aoe | action | aura
const CARDS = [

  // ── РОЛИ ─────────────────────────────────────────────────────────
  // Мета-карты, обозначающие сторону игрока. В колоде не участвуют —
  // выдаются перед раздачей.
  {
    id: 200,
    title: "Ниндзя",
    titleBgColor: "#0D233C",
    types: ["role"],
    qty: 4,
    group: "role",
    icons: [],
    tags: [],
    desc: "",
    img: "cards/card_role_ninja.png"
  },
  {
    id: 201,
    title: "Самурай",
    titleBgColor: "#891511",
    types: ["role"],
    qty: 3,
    group: "role",
    icons: [],
    tags: [],
    desc: "",
    img: "cards/card_role_samurai.png"
  },
  {
    id: 202,
    title: "Сёгун",
    titleBgColor: "#891511",
    types: ["role"],
    qty: 1,
    group: "role",
    icons: [],
    tags: [],
    desc: "",
    img: "cards/card_role_samurai.png"
  },
  {
    id: 203,
    title: "Placeholder",
    titleBgColor: "#891511",
    types: ["role"],
    qty: 1,
    group: "role",
    icons: [],
    tags: [],
    desc: "",
    img: "cards/card_todo_white.png"
  },

  // ── ОРУЖИЕ (стр. 1–5) ────────────────────────────────────────────
  {
    id: 1,
    title: "Катана",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "При наличии стойки вы наносите на 1 рану больше.",
    img: "cards/card_2_katana.png"
  },
  {
    id: 2,
    title: "Сюко",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_1_syuko.png"
  },
  {
    id: 3,
    title: "Канабо",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg3"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    img: "cards/card_3_kanabo.png"
  },
  {
    id: 4,
    title: "Боккэн",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg0"],
    tags: [],
    desc: "Вы берёте карту из колоды для себя или союзника в случае успешной атаки.",
    img: "cards/card_4_bokken.png"
  },
  {
    id: 5,
    title: "Кинжал предателя",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1", "rolectx"],
    tags: [],
    desc: "В стойке {ассасина} наносит на одну рану больше.[NL]От удара {ниндзи} нельзя защититься, и он игнорирует ловушки.",
    img: "cards/card_5_kinzhal_predatelya.png"
  },
  {
    id: 6,
    title: "Боевой веер",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    iconsOr: ["ranged", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_6_boevoy_veer.png"
  },
  {
    id: 7,
    title: "Кусаригама",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    iconsOr: ["melee2", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_7_kusarigama.png"
  },
  {
    id: 8,
    title: "Вакидзаси",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_8_wakizashi.png"
  },
  {
    id: 9,
    title: "Шипастый щит",
    types: ["weapon", "defense"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg1", "defense"],
    tags: [],
    desc: "Можно использовать как карту Защиты. В стойке {щитоносца} наносит на одну рану больше.",
    img: "cards/card_9_shipastyy_shchit.png"
  },
  {
    id: 10,
    title: "Тонфа",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    img: "cards/card_10_tonfa.png"
  },
  {
    id: 11,
    title: "Кама",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg3"],
    tags: [],
    desc: "",
    img: "cards/card_11_kama.png"
  },
  {
    id: 12,
    title: "Меч сёгуна",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg3"],
    tags: ["trash"],
    desc: "Только Сёгун может проводить прямую атаку этим оружием. Можно сыграть как вмешательство, чтобы передать эту карту Сёгуну в обмен на другую в закрытую.",
    img: "cards/card_12_mech_syoguna.png"
  },
  {
    id: 13,
    title: "Тэккокаги",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg4"],
    tags: [],
    desc: "",
    img: "cards/card_13_tekko_kagi.png"
  },
  {
    id: 14,
    title: "Нунчаки",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_14_nunchaki.png"
  },
  {
    id: 15,
    title: "Танто",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_15_mango.png"
  },
  {
    id: 16,
    title: "Тэкко",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg3"],
    tags: [],
    desc: "",
    img: "cards/card_16_mekko.png"
  },
  {
    id: 17,
    title: "Оно",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_17_ono.png"
  },
  {
    id: 317,
    title: "Ната",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_nata.png"
  },
  {
    id: 18,
    title: "Сай",
    types: ["weapon", "defense"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2", "defense"],
    tags: [],
    desc: "Это оружие можно использовать как Защиту.",
    img: "cards/card_18_say.png"
  },
  {
    id: 1018,
    title: "Манжи Сай",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_manji_sai.png"
  },
  {
    id: 19,
    title: "Явара",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    img: "cards/card_23_yavara.png"
  },
  {
    id: 20,
    title: "Боевой веер",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    iconsOr: ["melee1", "dmg2", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_6_boevoy_veer.png"
  },
  {
    id: 21,
    title: "Сай",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_18_say.png"
  },
  {
    id: 22,
    title: "Дзюттэ",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_21_dzyutte.png"
  },
  {
    id: 23,
    title: "Нунти Бо",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_22_nunti.png"
  },
  {
    id: 24,
    title: "Бо",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок теряет стойку в случае успешной атаки.",
    img: "cards/card_24_bo.png"
  },
  {
    id: 25,
    title: "Нодати",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg3"],
    tags: [],
    desc: "",
    img: "cards/card_25_nodati.png"
  },
  {
    id: 26,
    title: "Кёкэцусёгэ",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg2"],
    tags: [],
    desc: "В случае успешной атаки вы забираете карту из руки врага.",
    img: "cards/card_26_kyoketsusyoge.png"
  },
  {
    id: 27,
    title: "Манрики",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "В случае успешной атаки вы забираете карту из руки врага.",
    img: "cards/card_27_manriki.png"
  },
  {
    id: 28,
    title: "Нагината",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee_gt1", "dmg2"],
    tags: [],
    desc: "Может ударить на любом расстоянии более двух.",
    img: "cards/card_28_naginata.png"
  },
  {
    id: 29,
    title: "Яри",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "В стойке {всадника} наносит на одну рану больше.",
    img: "cards/card_29_yari.png"
  },
  {
    id: 30,
    title: "Камаяри",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "В стойке {всадника} наносит на одну рану больше.",
    img: "cards/card_31_kamayari.png"
  },
  {
    id: 31,
    title: "Яри",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1", "poison"],
    tags: ["poison"],
    desc: "В стойке {всадника} наносит на одну рану больше.",
    img: "cards/card_29_yari.png"
  },
  {
    id: 32,
    title: "Сюрикен",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_34_syuriken.png"
  },
  {
    id: 33,
    title: "Дайкю",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg2"],
    tags: [],
    desc: "В стойке {лучника} наносит на одну рану больше.",
    img: "cards/card_33_dayku.png"
  },
  {
    id: 1033,
    title: "Тэппо Юми",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_teppo_umi.png"
  },
  {
    id: 34,
    title: "Сюрикен",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison", ],
    desc: "",
    img: "cards/card_34_syuriken.png"
  },
  {
    id: 35,
    title: "Кунай",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    iconsOr: ["melee2", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_36_kunay.png"
  },
  {
    id: 36,
    title: "Бумеранг",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "В случае успешной атаки это оружие возвращается вам в руку.",
    img: "cards/card_37_bumerang.png"
  },
  {
    id: 37,
    title: "Дайкю",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg2", "poison"],
    tags: ["poison"],
    desc: "В стойке {лучника} наносит на одну рану больше.",
    img: "cards/card_33_dayku.png"
  },
  {
    id: 38,
    title: "Макибиши",
    types: ["weapon", "trap"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "trap"],
    tags: [],
    desc: "Можно использовать как ловушку, которая наносит одну рану атакующему в ответ.",
    img: "cards/card_38_makibishi.png"
  },
  {
    id: 39,
    title: "Дротик с ядом",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg0", "poison"],
    tags: ["poison"],
    desc: "Атака игнорирует ловушки и защиту, и вы берёте карту из колоды.",
    img: "cards/card_39_drotik_s_yadom.png"
  },
  {
    id: 40,
    title: "Кунай",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    iconsOr: ["melee1", "dmg2", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_36_kunay.png"
  },

  // ── ЛОВУШКИ (стр. 7) ─────────────────────────────────────────────
  {
    id: 41,
    title: "Силок",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: [],
    tags: [],
    desc: "Вы забираете у атакующего две карты.",
    img: "cards/card_41_silok.png"
  },
  {
    id: 42,
    title: "Чучело",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: [],
    tags: [],
    desc: "Атака не проходит, защищающийся берёт 2 карты из колоды.",
    img: "cards/card_42_chuchelo.png"
  },
  {
    id: 43,
    title: "Капкан",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: ["effect8"],
    tags: [],
    desc: "Атакующий получает две раны от владельца ловушки. Также эта карта переходит на атакующего эффектом, не дающим ему атаковать дальше дистанции в 1.",
    img: "cards/card_43_kapkan.png"
  },
  {
    id: 45,
    title: "Поганка",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Атакующий отравляется ядом, но если он уже отравлен, то вы наносите ему три раны.",
    img: "cards/card_45_poganka.png"
  },
  {
    id: 47,
    title: "Оскорбление",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: ["rolectx", "effect8"],
    tags: [],
    desc: "Вы оскорбляете атакующего. Для {самурая} это хуже смерти, и он получает эту карту как эффект бешенства, сбрасывая каждый раз карту при прямой атаке.",
    img: "cards/card_47_oskorblenie.png"
  },
  {
    id: 1048,
    title: "Дыхание Феникса",
    types: ["trap"],
    qty: 2,
    group: "trap",
    icons: [],
    tags: [],
    desc: "Если вы остались в живых после атаки, восстановите все жетоны жизни.",
    img: "cards/card_phoenix_breath.png"
  },
  {
    id: 1049,
    title: "Колотые раны",
    types: ["trap", "effect"],
    qty: 2,
    group: "trap",
    icons: ["effect8"],
    tags: [],
    desc: "Переходит эффектом на атакующего, и он лишается возможности использовать оружие для прямых атак.",
    img: "cards/card_glass_wounds.png"
  },

  // ── ЗАЩИТА (стр. 8) ──────────────────────────────────────────────
  {
    id: 48,
    title: "Защита",
    types: ["defense"],
    qty: 8,
    group: "defense",
    icons: [],
    tags: [],
    desc: "",
    img: "cards/card_48_zashchita.png"
  },
  {
    id: 49,
    title: "Скрытый кинжал",
    types: ["defense"],
    qty: 3,
    group: "defense",
    icons: ["hpctx"],
    tags: [],
    desc: "Атакующий получает 1 рану от вас. {На пороге вашей смерти} враг получает 3 раны.[NL]{При наличии ловушки} вы наносите ещё на одну рану больше.",
    img: "cards/card_49_skrytyy_kinzhal.png"
  },
  {
    id: 50,
    title: "Ядовитые наручи",
    types: ["defense"],
    qty: 2,
    group: "defense",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Атакующий получает отравление ядом.",
    img: "cards/card_50_yadovitye_naruchi.png"
  },
  {
    id: 51,
    title: "Идеальный момент",
    types: ["defense"],
    qty: 3,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Вы также берёте карту из колоды.",
    img: "cards/card_52_idealnyy_moment.png"
  },
  {
    id: 52,
    title: "Чудо Бенкэя",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Вы можете выбрать сколько ран вы хотите получить при атаке, и за каждую рану берёте карту из колоды.",
    img: "cards/card_53_vyderzka_samuray.png"
  },
  {
    id: 53,
    title: "Карманник",
    types: ["defense"],
    qty: 2,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Вы также забираете у атакующего случайную карту.",
    img: "cards/card_51_karmannik.png"
  },
  {
    id: 54,
    title: "Ошеломление",
    types: ["defense"],
    qty: 2,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Атакующий сбрасывает случайную карту.[NL]В стойке {щитоносца} вы берёте 1 карту из колоды.",
    img: "cards/card_54_oshelomlenie.png"
  },
  {
    id: 55,
    title: "Захват",
    types: ["defense"],
    qty: 3,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Вы забираете неметательное оружие врага себе в руку.[NL]{При наличии стойки} вы берёте дополнительно карту из колоды.",
    img: "cards/card_55_zakhvat.png"
  },
  {
    id: 44,
    title: "Рикошет",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: [],
    tags: [],
    desc: "Атака не проходит и обращается обратно, равная базовой силе оружия. Атакующий может защититься от рикошета.",
    img: "cards/card_44_rikoshet.png"
  },
  {
    id: 56,
    title: "Блок",
    types: ["defense", "intervention"],
    qty: 3,
    group: "defense",
    icons: ["intervention"],
    tags: [],
    desc: "Можно сыграть в любой момент за любого игрока как карту вмешательства.",
    img: "cards/card_56_blok.png"
  },

  // ── СТОЙКИ (стр. 9) ──────────────────────────────────────────────
  {
    id: 57,
    title: "Тень",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: [],
    tags: [],
    desc: "Вы считаетесь убитым для других игроков весь раунд, но в начале своего хода сбрасываете эту стойку.",
    img: "cards/card_57_ten.png"
  },
  {
    id: 58,
    title: "Всадник",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "Вы находитесь дальше от всех на 1 при атаках по вам. Ваши атаки могут достать дальше на 1. При совершении атак на дистанции 1 вы наносите на 1 рану больше.",
    img: "cards/card_58_vsadnik.png"
  },
  {
    id: 59,
    title: "Лотос",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "При выставлении восстановить два жетона жизни.[NL]Перед каждой фазой набора вы можете: восстановить жетон жизни любому игроку {ИЛИ} взять карту из колоды.",
    img: "cards/card_59_lotos.png"
  },
  {
    id: 60,
    title: "Щитоносец",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "Каждый раз при прямой атаке по вам снижаете урон на один. Дополнительно можете скинуть карту с руки за каждое снижение урона (не менее 1).[NL]Каждый раз, используя защиту, вы берёте одну карту из колоды.",
    img: "cards/card_60_shchitonosec.png"
  },
  {
    id: 61,
    title: "Мастер боя",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: [],
    tags: [],
    desc: "При совершении атаки можете выбрать нанести одну рану больше {ИЛИ} взять одну карту из колоды.[NL]{Совершая успешно прямую атаку} восстановите себе 1 жетон жизни.",
    img: "cards/card_61_master_boya.png"
  },
  {
    id: 62,
    title: "Капеллан",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: ["rolectx"],
    tags: [],
    desc: "Раз в свой ход вы можете: восстановить жетон жизни любому игроку -ИЛИ- снять яд или один эффект любому игроку, сбросив карту.[NL]{Самураи} не обязаны скидывать карту.",
    img: "cards/card_62_kapellan.png"
  },
  {
    id: 63,
    title: "Ассасин",
    types: ["stance"],
    qty: 2,
    group: "stance",
    icons: ["rolectx"],
    tags: [],
    desc: "При атаке по врагу вы можете: сделать вашу атаку отравленной ядом -ИЛИ- сбросив 2 карты, сделать врага беззащитным от атаки.[NL]{Ниндзя} обязаны скинуть лишь 1 карту.[NL]{Убив игрока} возьмите 2 карты из колоды. ",
    img: "cards/card_63_assassin.png"
  },
  {
    id: 1164,
    title: "Кэцубан",
    types: ["stance"],
    qty: 1,
    group: "stance",
    tags: [],
    desc: "В момент получения ран от оружия вы можете выбрать союзника, согласного с вами разделить в любой пропорции полученные раны.",
    img: "cards/card_cozuben.png",
  },
  {
    id: 1165,
    title: "Мусин",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["hpctx"],
    tags: [],
    desc: "{При полном здоровье} совершая прямые атаки вы берёте 2 карты из колоды.[NL]{На пороге смерти} ваши атаки наносят дополнительно 2 раны.",
    img: "cards/card_musin.png",
  },
  {
    id: 1166,
    title: "Лучник",
    types: ["stance"],
    qty: 1,
    group: "stance",
    tags: [],
    desc: "Все ваши атаки становятся метательными.[NL]Совершив успешную атаку по игроку с ловушкой, вы берёте 1 карту из колоды.",
    img: "cards/card_archer.png",
  },
  // ── МОДИФИКАТОРЫ (стр. 10–11) ─────────────────────────────────────
  {
    id: 64,
    title: "Флакон яда",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Ваша атака теперь накладывает отравление и наносит на 1 рану больше.",
    img: "cards/card_64_flakon_yada.png"
  },
  {
    id: 65,
    title: "Тамасэгири",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Ваша атака наносит на одну рану больше.",
    img: "cards/card_65_tochilo.png"
  },
  {
    id: 66,
    title: "Инь и Ян",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "Дальность и сила атаки меняются местами.",
    img: "cards/card_66_in_i_yan.png"
  },
  {
    id: 67,
    title: "Удар тени",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["rolectx"],
    tags: [],
    desc: "Ваша атака игнорирует ловушки и от неё невозможно защититься.[NL]{Ниндзя} наносят на 1 рану больше.[NL]{Самураи} штрафуются сбросом карты.",
    img: "cards/card_67_udar_teni.png"
  },
  {
    id: 68,
    title: "Выпад",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "+1 к силе атаки. Дальность вашей атаки увеличивается на 2.[NL]{При наличии стойки} наносите ещё на 1 рану больше.",
    img: "cards/card_68_vypad.png"
  },
  {
    id: 69,
    title: "Поступь ветра",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "От вашей атаки невозможно защититься, однако ловушки продолжают действовать. (ушло в удар тени)",
    img: "cards/card_69_postup_vetra.png"
  },
  {
    id: 70,
    title: "Гнев сёгуна",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Атаку можно провести даже по игроку при смерти.",
    img: "cards/card_70_gnev_syoguna.png"
  },
  {
    id: 71,
    title: "Кинжал похищения",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "В случае успешной атаки вы восстанавливаете себе столько жетонов жизни, сколько нанесли ран.",
    img: "cards/card_71_celebnyy_klinok.png"
  },
  {
    id: 72,
    title: "Порыв ярости",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "Атака наносит удар по двум целям одновременно. Однако сила и дальность снижаются на один. WAY TOO COMPLICATED",
    img: "cards/card_72_poryv_yarosti.png"
  },
  {
    id: 73,
    title: "Повязка камикадзе",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Ваша атака может бить на любом расстоянии и вы наносите на одну рану больше, но вы теряете один жетон жизни. Нельзя применить на пороге смерти.",
    img: "cards/card_73_povyazka_kamikadze.png"
  },
  {
    id: 74,
    title: "Бросок",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Меняет ваше оружие на метательное с базовой силой атаки 1.",
    img: "cards/card_75_brosok.png"
  },
  {
    id: 75,
    title: "Сокрушительный удар",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Итоговая сила атаки становится равна вашему количеству жетонов жизни.",
    img: "cards/card_74_sokrushitelnyy_udar.png"
  },
  {
    id: 76,
    title: "Кипящий яд",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Отравленный противник получит на две раны больше.",
    img: "cards/card_76_kipyashchiy_yad.png"
  },
  {
    id: 77,
    title: "Длань сёгуна",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы не тратите свою попытку атаки в данном ударе.[NL]{Самураи} наносят дополнительно 1 рану.[NL]{Ниндзя} штрафуются сбросом карты.",
    img: "cards/card_77_dlan_syoguna.png"
  },
  {
    id: 78,
    title: "Дух сёгуна",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: ["trash"],
    desc: "От вашей атаки невозможно защититься, и ловушки не действуют. (ушло в удар тени)",
    img: "cards/card_78_dukh_syoguna.png"
  },
  {
    id: 79,
    title: "Пронзительный удар",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Ваша атака оружием полностью игнорирует все бонусы от стойки, персонажа и эффектов цели.",
    img: "cards/card_80_pronzitelnyy_udar.png"
  },
  {
    id: 80,
    title: "Критический удар",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Сила атаки увеличивается на 2.",
    img: "cards/card_79_kriticheskiy_udar.png"
  },
  {
    id: 1081,
    title: "Финальный удар",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Финальная сила атаки равна количеству недостающих жетонов жизни цели.",
    img: "cards/card_final_strike.png"
  },
  {
    id: 1083,
    title: "Кубитори",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "+1 к силе атаки. При убийстве врага этой атакой вы можете забрать себе его стойку и любые эффекты.",
    img: "cards/card_kubitori.png"
  },
  {
    id: 1084,
    title: "Победный удар",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: [],
    tags: [],
    desc: "Ваше текущее количество жетонов победы добавляется к силе атаки.",
    img: "cards/card_victory_strike.png"
  },
  // ── ГРУППОВЫЕ ДЕЙСТВИЯ (стр. 12) ─────────────────────────────────
  {
    id: 81,
    title: "Целительные источники",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Полностью восстановите себе здоровье и снимите с себя любые эффекты и яд, остальные активные игроки +1 ХП. -ИЛИ- Все активные игроки +2 ХП и снимают яд.",
    img: "cards/card_81_celitelnyye_istochniki.png"
  },
  {
    id: 82,
    title: "Миротворцы",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Остальные активные игроки скидывают карту защиты или оружия, либо отдают вам карту из руки на свой выбор.",
    img: "cards/card_82_mirotvortsy.png"
  },
  {
    id: 83,
    title: "Потасовка",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Все остальные активные игроки теряют свою стойку и сбрасывают свою ловушку.",
    img: "cards/card_83_potasovka.png"
  },
  {
    id: 84,
    title: "Чайная церемония",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Вы берёте 4 карты из колоды, остальные активные игроки берут по 1 карте. -ИЛИ- Все активные игроки берут по 2 карты из колоды.",
    img: "cards/card_84_chaynaya_tseremoniya.png"
  },
  {
    id: 85,
    title: "Просветление",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["aoe"],
    tags: [],
    desc: "Все ловушки, кроме вашей, на столе открываются, но продолжают действовать. За каждую просветлённую ловушку вы берёте карту из колоды.",
    img: "cards/card_85_prosvietlenie.png"
  },
  {
    id: 86,
    title: "Вихрь ярости",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: ["draft"],
    desc: "Играется в паре с картой не метательного оружия с дальностью более одного. Минуя ловушки, активные игроки получают урон от оружия (без бонусов) или скидывают защиту. Тратит атаку.",
    img: "cards/card_86_vikhr_yarosti.png"
  },
  {
    id: 87,
    title: "Шквал огня",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту и за счёт каждой другой карты с руки метните в других метательным оружием силой 1. От этого можно защититься. Максимум 1 удар в одну цель. Тратит атаку.",
    img: "cards/card_shkval_ognya.png"
  },
  {
    id: 88,
    title: "Кислотный взрыв",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["poison", "charges"],
    tags: ["poison"],
    desc: "За каждое отравление на столе выбранный вами игрок теряет жетон жизни.",
    img: "cards/card_acid_explosion.png"
  },
  {
    id: 89,
    title: "Град стрел",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: ["trash"],
    desc: "Все ловушки на столе сбрасываются в сброс. (ушло в потасовку)",
    img: "cards/card_88_grad_strel.png"
  },
  {
    id: 90,
    title: "Боевой крик",
    types: ["aoe"],
    qty: 2,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Остальные активные игроки скидывают карту защиты или два жетона жизни.",
    img: "cards/card_89_boevoy_krik.png"
  },
  {
    id: 3091,
    title: "Обыск",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Остальные активные игроки выкладывают перед собой на своё усмотрение любую карту в открытую. Изучив карты, вы можете взять любую из них себе в руку.",
    img: "cards/card_obisk.png"
  },
  {
    id: 3092,
    title: "?Cбор клана 1?",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["charges"],
    tags: ["trash", "draft"],
    desc: "За каждого активного союзника, ваши союзника берут по карте из колоды.",
    img: "cards/card_todo.png"
  },
  {
    id: 3093,
    title: "?Cбор клана 2?",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["charges"],
    tags: ["draft", "trash"],
    desc: "За каждого активного союзника, ваши союзника восстанавливают 1 жетон жизни.",
    img: "cards/card_todo.png"
  },
  {
    id: 3094,
    title: "Крик возмездия",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["charges"],
    tags: [],
    desc: "Каждый враг получает атаку равную по силе количеству ваших союзников при смерти. От этого нельзя защититься.",
    img: "cards/card_redemption_cry.png"
  },
  {
    id: 1094,
    title: "Эстафета мечей",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Каждый активный игрок выбирает 1 карту со своей руки и кладёт её закрытой перед собой. Когда все выложили — карты сдвигаются на одну позицию по часовой стрелке (каждый получает закрытую карту соседа справа).",
    img: "cards/card_wave.png"
  },
  {
    id: 1137,
    title: "Военный совет",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "Все живые союзники выкладывают одну карту в открытую перед собой, вы выбираете какой из союзников получит какую. Нельзя остаться при своей карте.",
    img: "cards/card_forum.png"
  },
  {
    id: 1138,
    title: "Кровное родство",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: [],
    tags: [],
    desc: "На ваше усмотрение вы перераспределяете жетоны жизни между живыми союзниками.",
    img: "cards/card_blood_bound.png"
  },
  {
    id: 1139,
    title: "Плечом к плечу",
    types: ["aoe"],
    qty: 1,
    group: "aoe",
    icons: ["charges"],
    tags: [],
    desc: "Вы наносите 1 рану, за каждое скинутое от команды (максимум по 1 с игрока) оружие наносите дополнительно 1 рану.",
    img: "cards/card_shoulder_to_shoulder.png"
  },
  // ── ЭФФЕКТЫ постоянные/разовые (стр. 13–14) ──────────────────────
  {
    id: 91,
    title: "Метка убийцы",
    types: ["effect"],
    qty: 4,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Все атаки по вам наносят на одну рану больше, и атакующий берёт 1 карту из колоды.[NL]{Убивший вас игрок} берёт две карты из колоды.",
    img: "cards/card_90_metka_ubiytsy.png"
  },
  {
    id: 92,
    title: "Противоядие",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Вас нельзя отравить ядом. Текущее отравление снимается.",
    img: "cards/card_91_protivoyadie.png"
  },
  {
    id: 93,
    title: "Укус змеи",
    types: ["effect"],
    qty: 3,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Каждое лечение по игроку снижается на единицу. Также все негативные эффекты от отравления удваиваются. Пока вы отравлены, вы не можете пользоваться бонусами стойки.",
    img: "cards/card_92_ukus_zmeyi.png"
  },
  {
    id: 94,
    title: "Кагинава",
    types: ["effect"],
    qty: 3,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Атаки по вам могут быть произведены без ограничения дальности.",
    img: "cards/card_93_kaginava.png"
  },
  {
    id: 95,
    title: "Разоружение",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Выбранный игрок не может производить прямые атаки оружием.[NL]{Самураи} чтобы атаковать вас должны сбросить 1 карту.",
    img: "cards/card_94_razoruzhenie.png"
  },
  {
    id: 96,
    title: "Завеса дыма",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: ["trash"],
    desc: "TODO: Следующий игровой ход выбранный игрок будто при смерти. ЧТО-ТО сделать с этой картой! Может в стойку из вмешательства?",
    img: "cards/card_95_zavesa_dyma.png"
  },
  {
    id: 97,
    title: "Пыль в глаза",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Атаки игрока не могут бить дальше расстояния в единицу.",
    img: "cards/card_97_pyl_v_glaza.png"
  },
  {
    id: 99,
    title: "Чаша благовоний",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: ["charges"],
    tags: [],
    desc: "Выбранный игрок скидывает указанный вами эффект. За каждую дополнительно сброшенную карту можно скинуть ещё 1 эффект. За каждый такой скинутый эффект, вы восстанавливаете 1 жетон жизни любому игроку.",
    img: "cards/card_98_chasha_blagovoniy.png"
  },
  {
    id: 100,
    title: "Слабость",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Следующая атака не может нанести более одной раны.",
    img: "cards/card_99_slabost.png"
  },
  {
    id: 101,
    title: "Беззащитность",
    types: ["effect"],
    qty: 2,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Игрок не может защищаться от атак.",
    img: "cards/card_100_bezzashchitnost.png"
  },
  {
    id: 102,
    title: "Дух лидера",
    types: ["effect"],
    qty: 2,
    group: "effect",
    icons: [],
    tags: ["trash", "draft"],
    desc: "Выбранный игрок берёт на одну карту больше в фазе набора. TODO: remove?",
    img: "cards/card_101_dukh_lidera.png"
  },
  {
    id: 103,
    title: "Бессилие",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "За ход вы можете сделать на одну прямую атаку меньше.",
    img: "cards/card_102_bessilie.png"
  },
  {
    id: 104,
    title: "Эгида",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: ["trash"],
    desc: "Выбранный игрок автоматически защищается от атаки. Новая механика игра и так позволяет многим помонать зашищаться.",
    img: "cards/card_103_egida.png"
  },
  {
    id: 4104,
    title: "Проклятье",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: [],
    tags: [],
    desc: "Получая любой вид урона, вы получаете на 2 раны больше. Проклятье переходит на убившего вас игрока.",
    img: "cards/card_curse.png"
  },
  {
    id: 5104,
    title: "Доспех",
    types: ["effect"],
    qty: 2,
    group: "effect",
    icons: [],
    tags: ["toPrint"],
    desc: "Сложность атак по вам увеличивается на 1.",
    img: "cards/card_armor.png"
  },

  // ── ДЕЙСТВИЯ (стр. 15–16) ─────────────────────────────────────────
  {
    id: 105,
    title: "Васаби",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: [],
    tags: [],
    desc: "Выбранный игрок избавляется от яда, получает жетон жизни и берёт одну карту из колоды.",
    img: "cards/card_104_vasabi.png"
  },
  {
    id: 106,
    title: "Зов предков",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Поменяйте эту карту на любую из сброса не глубже последних 10, но не ранее последних 3.",
    img: "cards/card_105_zov_predkov.png"
  },
  {
    id: 107,
    title: "Швы",
    types: ["action"],
    qty: 4,
    group: "action",
    icons: ["hpctx"],
    tags: [],
    desc: "Любой выбранный активный игрок восстанавливает 2 жетона жизни. В стойке {капеллана} восстанавливает на 1 жизнь больше.[NL]{На пороге вашей смерти} вы можете вылечить другого игрока на 3 жизни.",
    img: "cards/card_106_shvy.png"
  },
  {
    id: 108,
    title: "Сэппуку",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы выкладываете все карты перед собой в открытую, ваши активные союзники могут забрать любые ваши карты себе, не превышая ограничение в 8 карт, остальное идёт в сброс. Потом вы умираете и победное очко другому игроку. Таким образом нельзя потерять последнее победное очко.[NL]{Ниндзя} не могут совершать Сэппуку.",
    img: "cards/card_107_seppuku.png"
  },
  {
    id: 109,
    title: "Саке",
    types: ["action"],
    qty: 4,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сбросьте эту карту, чтобы взять 1 новую из колоды. Далее за каждую сброшенную карту (не более двух) берите дополнительно 1 карту из колоды. {Союзники} могут вам помочь в доборе, сбрасывая свои карты, но не более двух каждый.",
    img: "cards/card_108_sake.png"
  },
  {
    id: 110,
    title: "Боевой банан",
    types: ["action"],
    qty: 2,
    group: "action",
    icons: [],
    tags: ["draft", "trash"],
    desc: "Другой выбранный активный игрок скидывает свою текущую стойку, за это вы берёте карту. Или можете сбросить эту карту, чтобы взять две новых из колоды. TODO: remove carD entirelly? Or make something else based on having a condition of having STAANCE?",
    img: "cards/card_46_boevoy_banan.png"
  },
  {
    id: 111,
    title: "Предательство",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы сбрасываете победное очко в сброс (если не последнее), и за это получаете семь карт из колоды. Не считается смертью.[NL]{Самураи} не могут предавать.",
    img: "cards/card_110_predatelstvo.png"
  },
  {
    id: 112,
    title: "Сапёр",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "{Самурай} может обезвредить ловушку, скинув 1 жетон жизни.[NL]{Ниндзя} может украсть ловушку.[NL]Вне зависимости от роли, можете скинуть эту карту, чтобы взять две новых из колоды.",
    img: "cards/card_111_sapyor.png"
  },
  {
    id: 113,
    title: "Эквилибриум",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Количество жетонов жизни выбранного игрока становится равно вашему.[NL]{Ниндзя} должен сбросить одну карту для совершения действия.",
    img: "cards/card_112_ekvilibrium.png"
  },
  {
    id: 114,
    title: "Передышка",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: ["hpctx"],
    tags: [],
    desc: "Восстановите все недостающие жетоны жизни. Любой другой игрок на ваш выбор берёт одну карту из колоды.[NL]{При полном здоровье} вместо одной карты — две, и можете взять карты себе.",
    img: "cards/card_113_peredyshka.png"
  },
  {
    id: 115,
    title: "Ясновидение",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Выбранный игрок показывает всем свои карты с руки до следующего действия.[NL]{Ниндзя} может забрать любую из карт себе.",
    img: "cards/card_114_yasnovidenie.png"
  },
  {
    id: 116,
    title: "Яд фугу",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Отравляет выбранного активного игрока.",
    img: "cards/card_116_yad_fugu.png"
  },
  {
    id: 117,
    title: "Обмен душ",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: ["rolectx"],
    tags: [],
    desc: "Вы меняетесь с выбранным игроком количеством жетонов жизни.[NL]{Самурай} должен сбросить одну карту для совершения действия.",
    img: "cards/card_115_obmen_dush.png"
  },
  {
    id: 118,
    title: "Магатама",
    types: ["action"],
    qty: 2,
    group: "action",
    icons: [],
    tags: [],
    desc: "Либо сыграйте эту карту, чтобы взять 4 новых из колоды, либо оставьте, чтобы получить победное очко.",
    img: "cards/card_117_dayme.png"
  },
  {
    id: 119,
    title: "Переливание крови",
    types: ["action"],
    qty: 3,
    group: "action",
    icons: [],
    tags: ["trash"],
    desc: "Очищает любого игрока от отравления и передаёт его любому другому. UPD: перешло в куклу вуду",
    img: "cards/card_118_perelivanie_krovi.png"
  },
  {
    id: 120,
    title: "Жертва крови",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сыграв эту карту, берите за каждый сброшенный жетон жизни (кроме последнего) новую карту из колоды.",
    img: "cards/card_119_zhertva_krovi.png"
  },
  {
    id: 1121,
    title: "Кампо",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сыграв эту карту, можете сбросить любое необходимое количество карт, восстановив за каждую 1 жизнь.",
    img: "cards/card_kampo.png"
  },
  {
    id: 1122,
    title: "Смертные муки",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сыграв эту карту, возьмите по 1 карте из колоды за каждый недостающий жетон жизни.[NL]{Если вы отравлены}, возьмите дополнительно 1 карту ко всему добору.",
    img: "cards/card_smertnie_muki.png"
  },
  {
    id: 31121,
    title: "Горячая картошка",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "В открытую передайте эту карту любому активному игроку, взамен он обязан вам дать одну карту по своему желанию в закрытую. Эту карту нельзя положить в сброс, только обратно в колоду сверху.",
    img: "cards/card_hot_potato.png"
  },
  {
    id: 1122,
    title: "Мародёр",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Заставьте мёртвого игрока выложить все карты на стол, и можете забрать любые 2 из них. После карты опять скрываются. У живых игроков можно просто своровать 2 случайных карты.",
    img: "cards/card_loot_corpse.png"
  },
  {
    id: 1123,
    title: "Зеркало души",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы вызвать действия, совершаемые персонажем любого игрока {после смерти}, как будто он ваш союзник.",
    img: "cards/card_soul_mirror.png"
  },
  {
    id: 1124,
    title: "Лазутчик",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы забираете себе ауру выбранного активного игрока.",
    img: "cards/card_spy.png"
  },
  // ── ВМЕШАТЕЛЬСТВА (стр. 17) ───────────────────────────────────────
  {
    id: 1125,
    title: "Эстафета",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Вы можете передать свою ауру союзнику, или по согласию забрать себе его ауру.",
    img: "cards/card_baton.png"
  },
  {
    id: 121,
    title: "Исцеление",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Восстановите все жетоны жизни отравленному ядом игроку и снимите само отравление.",
    img: "cards/card_120_istselenie.png"
  },
  {
    id: 122,
    title: "Смерть от фугу",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы нанести две раны отравленному ядом игроку.",
    img: "cards/card_121_smert_ot_fugu.png"
  },
  {
    id: 123,
    title: "Имбирь",
    types: ["intervention"],
    qty: 2,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы восстановить любому игроку один жетон жизни.",
    img: "cards/card_122_imbir.png"
  },
  {
    id: 124,
    title: "Удар дракона",
    types: ["intervention"],
    qty: 2,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы нанести одну рану любому выбранному игроку.",
    img: "cards/card_123_udar_drakona.png"
  },
  {
    id: 125,
    title: "Подвиг",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["hpctx", "rolectx"],
    tags: [],
    desc: "Сыграйте эту карту, чтобы перенаправить прямую атаку оружия на себя.[NL]{На пороге вашей смерти} ваши союзники берут по 1 карте из колоды.[NL]{Самураи} при этом получают на одну рану меньше.",
    img: "cards/card_124_podvig.png"
  },
  {
    id: 126,
    title: "Рука помощи",
    types: ["intervention"],
    qty: 4,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Сыграйте эту карту, чтобы передать любому игроку в закрытую любую другую карту из своей руки. -ИЛИ- Сыграйте эту карту, чтобы заставить другого игрока передать вам в закрытую любую карту на его выбор.",
    img: "cards/card_125_ruka_pomoshchi.png"
  },
  {
    id: 127,
    title: "Весточка",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: ["trash"],
    desc: "Сыграйте эту карту, чтобы передать любому игроку в закрытую любую другую карту из своей руки. (ушло в руку помощи)",
    img: "cards/card_126_vestochka.png"
  },
  {
    id: 128,
    title: "Симулянт",
    types: ["intervention", "effect"],
    qty: 3,
    group: "intervention",
    icons: ["effect8"],
    tags: [],
    desc: "Выбранный игрок симулирует смерть (при его согласии), оставляя один жетон жизни. Следующий раунд он при смерти. В начале хода игрока эффект пропадает.",
    img: "cards/card_127_simulyant.png"
  },
  {
    id: 1029,
    title: "Осколки",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Уничтожает сыгранное оружие на столе, карта идёт в сброс, а атака отменяется, не тратя попытку.",
    img: "cards/card_shards.png"
  },
  {
    id: 1030,
    title: "Сон Ёкая",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: [],
    tags: [],
    desc: "Следующее действие выбранного игрока завершит его ход. Сюда не входит скидывание парных карт.",
    img: "cards/card_dream_of_ekai.png"
  },

  // ── ПРОЧИЕ ДЕЙСТВИЯ (стр. 18) ─────────────────────────────────────
  {
    id: 129,
    title: "Воровство",
    types: ["action"],
    qty: 2,
    group: "action",
    icons: [],
    tags: [],
    desc: "Заберите одну случайную карту с руки любого активного игрока.",
    img: "cards/card_128_vorovstvo.png"
  },
  {
    id: 130,
    title: "Кукла вуду",
    types: ["action"],
    qty: 4,
    group: "action",
    icons: [],
    tags: [],
    desc: "Можете выбрать отравление или любой эффект на столе и переложить его на любого игрока.",
    img: "cards/card_129_kukla_vudu.png"
  },
  {
    id: 131,
    title: "Дурман",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["trash"],
    desc: "Вы забираете выбранный эффект игрока на себя. UPD: ушло в куклу вуду",
    img: "cards/card_130_durman.png"
  },
  {
    id: 132,
    title: "Кэцу нуги",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Забираете у игрока жетон жизни и добавляете его себе.[NL]{Если вы отравлены}, то передаёте игроку отравление.",
    img: "cards/card_131_sifon_zhizni.png"
  },
  {
    id: 133,
    title: "Перехват",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: ["trash"],
    desc: "TODO: нужна ли карта с переделой Сапёра? Вы забираете ловушку другого игрока себе в руку. UPD: Into sapper",
    img: "cards/card_132_obman.png"
  },
  {
    id: 1133,
    title: "Камикадзе",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы сбрасываете все карты с руки, но убиваете выбранного игрока.",
    img: "cards/card_kamikadze.png"
  },
  {
    id: 1134,
    title: "Ва банк",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы меняетесь полностью картами в руке в закрытую с выбранным активным игроком.",
    img: "cards/card_va_bank.png"
  },
  {
    id: 1135,
    title: "Ёкай",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Объявляете один из четырёх типов карт: Оружие, Ловушка, Стойка или Защита. Берёте из сброса в обратном порядке первую попавшуюся карту заданного типа.",
    img: "cards/card_ekai.png"
  },
  {
    id: 1136,
    title: "Укол вслепую",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "У выбранного игрока текущее и недостающее количество жетонов жизни меняются местами.",
    img: "cards/card_motusa.png"
  },
  // ── ПЕРСОНАЖИ (стр. 19) ───────────────────────────────────────────
  {
    id: 135,
    title: "Усивака",
    subtitle: "Безрассудный налётчик",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: [],
    desc: "Каждый раз, получая раны, вы берёте одну карту из колоды. Вместо вынужденного сброса карты можно тратить жетон жизни." +
          "[NL]{После вашей смерти} враги получают 1 рану.",
    img: "cards/card_135_usivaka.png"
  },
  {
    id: 136,
    title: "Таранага",
    subtitle: "Искусный стратег",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: [],
    desc: "В фазе набора вы берёте дополнительную карту и можете брать из сброса. " +
          "В случае воровства, ошеломления или реакции на групповые действия сами выбираете, какую карту отдавать." +
          "[NL]{После вашей смерти} ваши союзники берут по одной карте из колоды.",
    img: "cards/card_136_taranaga.png"
  },
  {
    id: 137,
    title: "Сайго",
    subtitle: "Последний самурай",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: [],
    desc: "Раз в ход вы можете передвинуть свою активную стойку, или стойку с руки, к другому игроку, у которого её нет перед собой. В фазе набора за каждую стойку на столе берите дополнительно 1 карту." +
          "[NL]{После вашей смерти} вы не теряете стойку, а все союзники с выставленной стойкой получают по 1 карте из колоды и восполняют 1 жетон жизни.",
    img: "cards/card_138_kokoro.png"
  },
  {
    id: 138,
    title: "Хандзо",
    subtitle: "Неуловимый синоби",
    hp: 4,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: [],
    desc: "Вы можете использовать оружие для защиты от прямых атак, но при этом получаете одну рану. Можете скидывать карты защиты, чтобы взять две новых из колоды." +
          "[NL]{После вашей смерти} можете отдать каждому союзнику по одной карте защиты в открытую.",
    img: "cards/card_139_handzo.png"
  },

  {
    id: 142,
    title: "Норио",
    subtitle: "Мирный монах",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: [],
    desc: "Можете сбросить карту оружия раз за ход, чтобы восстановить жизнь любому игроку или взять две карты из колоды." +
          "[NL]{После вашей смерти} можете отдать каждому союзнику по одной карте оружия в открытую.",
    img: "cards/card_142_norio.png"
  },
  {
    id: 139,
    title: "Иё",
    subtitle: "Знаток ловушек",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: [],
    desc: "Раз в ход можете передвинуть свою активную ловушку к союзному игроку, у которого её нет перед собой. В фазе набора за каждую ловушку на столе берите дополнительно 1 карту." +
          "[NL]{После вашей смерти} ловушки врагов просвещаются.",
    img: "cards/card_140_iyo.png"
  },
  {
    id: 140,
    title: "Така",
    subtitle: "Ловкая воровка",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: [],
    desc: "Раз в ход вы можете забрать на усмотрение игрока карту или отдать ему свою. Раз в ход вы можете сбросить 2 карты, чтобы взять 3 новых из колоды." +
          "[NL]{После вашей смерти} вы можете раздать по 2 карты каждому из ваших союзников в закрытую.",
    img: "cards/card_141_taka.png"
  },
  {
    id: 145,
    title: "Манасэ",
    subtitle: "Врач Сэнгоку",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "За каждый восстановленный жетон здоровья в команде вы берёте карту из колоды. Можете перенаправить лечебный эффект с себя на союзника. " +
          "[NL]{После вашей смерти} каждый союзник восстанавливает 1 жетон жизни, не давая вам карты из колоды.",
    img: "cards/card_145_manase.png"
  },
  {
    id: 146,
    title: "Минамото",
    subtitle: "Дух оспы Идзу",
    hp: 5,
    types: ["character"],
    qty: 1,
    group: "character",
    icons: [],
    tags: ["toPrint"],
    desc: "Если вы отравлены, то все ваши атаки автоматически отравлены, и вы не испытываете отрицательных эффектов от яда. В фазе набора за каждого отравленного игрока на столе берите дополнительно одну карту." +
          "[NL]{После вашей смерти} все враги отравляются ядом, а союзники исцеляются от яда.",
    img: "cards/card_minamoto.png"
  },

  // ── КОМАНДНЫЕ КАРТЫ (Team Aura / Enemy Objective) ────────────────
  // Выкладываются перед одним игроком (носителем), действуют как «знамя» на всю
  // его команду. Лимит — одна командная карта на команду одновременно. Носитель
  // становится приоритетной целью противника. См. mechanics/new-mechanics-ideas.md
  // №6 и mechanics/team_cards_ideas.html.
  {
    id: 1200,
    title: "Знамя лидера",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Все атаки {союзников} наносят +1 рану.",
    img: "cards/card_leader.png"
  },
  {
    id: 1201,
    title: "Закрытый тыл",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Все {союзники} получают на одну рану меньше от любой прямой атаки (не менее 1).",
    img: "cards/card_rare.png"
  },
  {
    id: 1202,
    title: "Ровный строй",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Сложность атак по вашей команде увеличивается на 1.",
    img: "cards/card_march.png"
  },
  {
    id: 1203,
    title: "Бочка зловония",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Все прямые атаки {союзников} оружием автоматически отравлены, как будто использовалось ядовитое оружие.[NL]{Носитель} получает отравление ядом.",
    img: "cards/card_87_bochka_zlovoniya.png"
  },
  {
    id: 1204,
    title: "Спина к спине",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Любой {союзник} может разыграть карту защиты с руки как вмешательство в защиту другого союзника. Бонусы карты защиты при этом не сохраняются.",
    img: "cards/card_back_to_back.png"
  },
  {
    id: 1205,
    title: "Стратег",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "В фазе набора каждый {союзник} берёт +1 карту из колоды.",
    img: "cards/card_camp.png"
  },
  {
    id: 1206,
    title: "Дымовая завеса",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "{Враги} не могут проводить метательные атаки.",
    img: "cards/card_95_zavesa_dyma.png"
  },
  {
    id: 1207,
    title: "Присяга",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Любой живой {союзник} может по согласию принять прямую атаку оружия по другому союзнику на себя (как Подвиг), но получает на 1 рану больше.",
    img: "cards/card_war_duty.png"
  },
  {
    id: 1208,
    title: "Полевая медицина",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "В начале хода любой {союзник} восстанавливает 1 жетон жизни.",
    img: "cards/card_hospital.png"
  },
  {
    id: 1209,
    title: "Часовой",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "{Враги} после нанесения ран прямой атакой по вашим союзникам получают от носителя ауры 1 рану.[NL]{Носитель} не может пользоваться метательным оружием.",
    img: "cards/card_warden.png"
  },
  {
    id: 1210,
    title: "Арсенал",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "При совершении прямой атаки оружием (до действий защищающегося), любой {союзник} может с согласия атакующего выставить оружие (как вмешательство), а его забрать себе.",
    img: "cards/card_arsenal.png"
  },

  {
    id: 1211,
    title: "Подпольная сеть",
    types: ["aura"],
    qty: 1,
    group: "aura",
    icons: [],
    tags: ["toPrint"],
    desc: "Раз в свой ход любой {союзник} может обменяться с соратником в закрытую по согласию картами.",
    img: "cards/card_discreete_deal.png"
  },
];