// Допустимые типы: weapon | trap | character | modifier | defense | stance | effect | intervention | group | action
const CARDS = [

  // ── ОРУЖИЕ (стр. 1–5) ────────────────────────────────────────────
  {
    id: 1,
    title: "Катана",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_2_katana.png"
  },
  {
    id: 2,
    title: "Сюко",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_1_syuko.png"
  },
  {
    id: 3,
    title: "Канабо",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg3"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    img: "cards/card_3_kanabo.png"
  },
  {
    id: 4,
    title: "Боккэн",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg0"],
    tags: [],
    desc: "Вы берёте карту из колоды в случае успешной атаки.",
    img: "cards/card_4_bokken.png"
  },
  {
    id: 5,
    title: "Кинжал предателя",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "Нельзя защититься. Игнорирует ловушки. Можно производить атаку будучи в дуэли. Нельзя атаковать Сёгуна.",
    img: "cards/card_5_kinzhal_predatelya.png"
  },
  {
    id: 6,
    title: "Боевой веер",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "Можно воспользоваться либо как обычным оружием 1/2, либо как метательным оружием 3/1.",
    img: "cards/card_6_boevoy_veer.png"
  },
  {
    id: 7,
    title: "Кусаригама",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee2", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_7_kusarigama.png"
  },
  {
    id: 8,
    title: "Вакидзаси",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_8_wakizashi.png"
  },
  {
    id: 9,
    title: "Шипастый щит",
    types: ["weapon", "defense"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1", "defense"],
    tags: [],
    desc: "Можно использовать как карту Защиты.",
    img: "cards/card_9_shipastyy_shchit.png"
  },
  {
    id: 10,
    title: "Тонфа",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    img: "cards/card_10_tonfa.png"
  },
  {
    id: 11,
    title: "Кама",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg3"],
    tags: [],
    desc: "",
    img: "cards/card_11_kama.png"
  },
  {
    id: 12,
    title: "Меч сёгуна",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg3"],
    tags: ["trash"],
    desc: "Только Сёгун может проводить прямую атаку этим оружием. Можно сыграть как вмешательство, чтобы передать эту карту Сёгуну в обмен на другую в закрытую.",
    img: "cards/card_12_mech_syoguna.png"
  },
  {
    id: 13,
    title: "Тэккокаги",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg4"],
    tags: [],
    desc: "",
    img: "cards/card_13_tekko_kagi.png"
  },
  {
    id: 14,
    title: "Нунчаки",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_14_nunchaki.png"
  },
  {
    id: 15,
    title: "Танто",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_15_mango.png"
  },
  {
    id: 16,
    title: "Тэкко",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg3"],
    tags: [],
    desc: "",
    img: "cards/card_16_mekko.png"
  },
  {
    id: 17,
    title: "Оно",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: ["toPrint"],
    desc: "",
    img: "cards/card_17_ono.png"
  },
  {
    id: 317,
    title: "Ната",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: ["toPrint"],
    desc: "",
    img: "cards/card_nata.png"
  },
  {
    id: 18,
    title: "Сай",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_18_say.png"
  },
  {
    id: 19,
    title: "Явара",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок скидывает случайную карту в случае успешной атаки.",
    img: "cards/card_23_yavara.png"
  },
  {
    id: 20,
    title: "Отравленный боевой веер",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee2", "dmg1", "poison"],
    tags: ["poison"],
    desc: "Можно воспользоваться либо как обычным оружием 1/2, либо как метательным оружием 3/1.",
    img: "cards/card_6_boevoy_veer.png"
  },
  {
    id: 21,
    title: "Отравленный сай",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_18_say.png"
  },
  {
    id: 22,
    title: "Дзюттэ",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_21_dzyutte.png"
  },
  {
    id: 23,
    title: "Нунти",
    types: ["weapon"],
    qty: 1,
    group: "weapon",
    icons: ["melee1", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_22_nunti.png"
  },
  {
    id: 24,
    title: "Бо",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "Атакуемый игрок теряет стойку в случае успешной атаки.",
    img: "cards/card_24_bo.png"
  },
  {
    id: 25,
    title: "Нодати",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg3"],
    tags: [],
    desc: "Атакуемый игрок теряет стойку в случае успешной атаки.",
    img: "cards/card_25_nodati.png"
  },
  {
    id: 26,
    title: "Кёкэцусёгэ",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg2"],
    tags: [],
    desc: "В случае успешной атаки вы забираете карту из руки врага.",
    img: "cards/card_26_kyoketsusyoge.png"
  },
  {
    id: 27,
    title: "Манрики",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "В случае успешной атаки вы забираете карту из руки врага.",
    img: "cards/card_27_manriki.png"
  },
  {
    id: 28,
    title: "Нагината",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee_gt1", "dmg2"],
    tags: [],
    desc: "Может ударить на любом расстоянии более двух.",
    img: "cards/card_28_naginata.png"
  },
  {
    id: 29,
    title: "Яри",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_29_yari.png"
  },
  {
    id: 30,
    title: "Камаяри",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_31_kamayari.png"
  },
  {
    id: 31,
    title: "Отравленный яри",
    types: ["weapon"],
    qty: 2,
    group: "weapon",
    icons: ["melee2", "dmg2", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_29_yari.png"
  },
  {
    id: 32,
    title: "Сюрикен",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "",
    img: "cards/card_34_syuriken.png"
  },
  {
    id: 33,
    title: "Дайкю",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_33_dayku.png"
  },
  {
    id: 34,
    title: "Отравленный сюрикен",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_34_syuriken.png"
  },
  {
    id: 35,
    title: "Кунай",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg2"],
    tags: [],
    desc: "",
    img: "cards/card_36_kunay.png"
  },
  {
    id: 36,
    title: "Бумеранг",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg1"],
    tags: [],
    desc: "В случае успешной атаки это оружие возвращается вам в руку.",
    img: "cards/card_37_bumerang.png"
  },
  {
    id: 37,
    title: "Отравленный дайкю",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg2", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_33_dayku.png"
  },
  {
    id: 38,
    title: "Макибиши",
    types: ["weapon", "trap"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg0", "trap"],
    tags: [],
    desc: "Можно использовать как ловушку, которая наносит одну рану атакующему в ответ.",
    img: "cards/card_38_makibishi.png"
  },
  {
    id: 39,
    title: "Дротик с ядом",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison"],
    desc: "Атака игнорирует ловушки и защиту, и вы берёте карту из колоды.",
    img: "cards/card_39_drotik_s_yadom.png"
  },
  {
    id: 40,
    title: "Отравленный кунай",
    types: ["weapon"],
    qty: 3,
    group: "weapon",
    icons: ["ranged", "dmg1", "poison"],
    tags: ["poison"],
    desc: "",
    img: "cards/card_36_kunay.png"
  },

  // ── ЛОВУШКИ (стр. 7) ─────────────────────────────────────────────
  {
    id: 41,
    title: "Силок",
    types: ["trap"],
    qty: 1,
    group: "trap",
    icons: ["trap"],
    tags: [],
    desc: "ЛОВУШКА. Вы забираете у атакующего две карты.",
    img: "cards/card_41_silok.png"
  },
  {
    id: 42,
    title: "Чучело",
    types: ["trap"],
    qty: 1,
    group: "trap",
    icons: ["trap"],
    tags: [],
    desc: "ЛОВУШКА. Атака не проходит.",
    img: "cards/card_42_chuchelo.png"
  },
  {
    id: 43,
    title: "Капкан",
    types: ["trap"],
    qty: 1,
    group: "trap",
    icons: ["trap"],
    tags: [],
    desc: "ЛОВУШКА. Атакующий получает две раны от владельца ловушки.",
    img: "cards/card_43_kapkan.png"
  },
  {
    id: 44,
    title: "Рикошет",
    types: ["trap"],
    qty: 1,
    group: "trap",
    icons: ["trap"],
    tags: [],
    desc: "ЛОВУШКА. Изначальная атака не проходит и обращается обратно, равная силе оружия. Атакующий может защититься от рикошета.",
    img: "cards/card_44_rikoshet.png"
  },
  {
    id: 45,
    title: "Поганка",
    types: ["trap"],
    qty: 1,
    group: "trap",
    icons: ["trap", "poison"],
    tags: ["poison"],
    desc: "ЛОВУШКА. Враг отравляется ядом. Если он уже отравлен, то получает 1 рану.",
    img: "cards/card_45_poganka.png"
  },
  {
    id: 46,
    title: "Боевой банан",
    types: ["trap"],
    qty: 1,
    group: "trap",
    icons: ["trap"],
    tags: [],
    desc: "ЛОВУШКА. Атакующий теряет свою стойку и сбрасывает две карты с руки на ваш выбор.",
    img: "cards/card_46_boevoy_banan.png"
  },
  {
    id: 47,
    title: "Оскорбление",
    types: ["trap"],
    qty: 1,
    group: "trap",
    icons: ["trap"],
    tags: [],
    desc: "ЛОВУШКА. Вы оскорбляете атакующего.",
    img: "cards/card_47_oskorblenie.png"
  },

  // ── ЗАЩИТА (стр. 8) ──────────────────────────────────────────────
  {
    id: 48,
    title: "Защита",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense"],
    tags: [],
    desc: "",
    img: "cards/card_48_zashchita.png"
  },
  {
    id: 49,
    title: "Скрытый кинжал",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense"],
    tags: [],
    desc: "ЗАЩИТА ~ Атакующий получает одну рану от вас.",
    img: "cards/card_49_skrytyy_kinzhal.png"
  },
  {
    id: 50,
    title: "Ядовитые наручи",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense", "poison"],
    tags: ["poison"],
    desc: "ЗАЩИТА ~ Атакующий получает отравление ядом.",
    img: "cards/card_50_yadovitye_naruchi.png"
  },
  {
    id: 51,
    title: "Идеальный момент",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense"],
    tags: [],
    desc: "ЗАЩИТА ~ Вы забираете у атакующего случайную карту.",
    img: "cards/card_52_idealnyy_moment.png"
  },
  {
    id: 52,
    title: "Выдержка самурая",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense"],
    tags: [],
    desc: "ЗАЩИТА ~ Вы также берёте карту из колоды.",
    img: "cards/card_53_vyderzka_samuray.png"
  },
  {
    id: 53,
    title: "Карманник",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense"],
    tags: [],
    desc: "ЗАЩИТА ~ Вы можете выбрать сколько ран вы хотите получить при атаке, и за каждую рану берёте карту из колоды.",
    img: "cards/card_51_karmannik.png"
  },
  {
    id: 54,
    title: "Ошеломление",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense"],
    tags: [],
    desc: "ЗАЩИТА ~ Атакующий сбрасывает случайную карту.",
    img: "cards/card_54_oshelomlenie.png"
  },
  {
    id: 55,
    title: "Захват",
    types: ["defense"],
    qty: 1,
    group: "defense",
    icons: ["defense"],
    tags: [],
    desc: "ЗАЩИТА ~ Вы забираете неметательное оружие врага себе в руку.",
    img: "cards/card_55_zakhvat.png"
  },
  {
    id: 56,
    title: "Блок",
    types: ["defense", "intervention"],
    qty: 1,
    group: "defense",
    icons: ["defense", "intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО~ЗАЩИТА. Можно сыграть в любой момент за любого игрока.",
    img: "cards/card_56_blok.png"
  },

  // ── СТОЙКИ (стр. 9) ──────────────────────────────────────────────
  {
    id: 57,
    title: "Тень",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["stance"],
    tags: [],
    desc: "СТОЙКА ~ Вы обескровлены для других игроков весь раунд, но в начале своего хода сбрасываете эту стойку.",
    img: "cards/card_57_ten.png"
  },
  {
    id: 58,
    title: "Всадник",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["stance"],
    tags: [],
    desc: "СТОЙКА ~ Вы находитесь дальше от всех на единицу при атаках по вам. Ваши атаки могут достать дальше на один.",
    img: "cards/card_58_vsadnik.png"
  },
  {
    id: 59,
    title: "Лотос",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["stance"],
    tags: [],
    desc: "СТОЙКА ~ При выставлении восстановить два жетона жизни и перед каждой фазой набора вы можете: восстановить жетон жизни любому игроку ИЛИ снять яд или один эффект любому игроку, сбросив карту.",
    img: "cards/card_59_lotos.png"
  },
  {
    id: 60,
    title: "Щитоносец",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["stance"],
    tags: [],
    desc: "СТОЙКА ~ Каждый раз при прямой атаке по вам снижаете урон на один. Дополнительно можете скинуть карту с руки за каждое снижение урона (не менее одного).",
    img: "cards/card_60_shchitonosec.png"
  },
  {
    id: 61,
    title: "Мастер боя",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["stance"],
    tags: [],
    desc: "СТОЙКА ~ После каждой успешной атаки вы наносите врагу на одну рану больше и можете взять одну карту из колоды.",
    img: "cards/card_61_master_boya.png"
  },
  {
    id: 62,
    title: "Капеллан",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["stance"],
    tags: [],
    desc: "СТОЙКА ~ Раз в свой ход вы можете: восстановить жетон жизни любому игроку ИЛИ снять яд или один эффект любому игроку, сбросив карту.",
    img: "cards/card_62_kapellan.png"
  },
  {
    id: 63,
    title: "Ассасин",
    types: ["stance"],
    qty: 1,
    group: "stance",
    icons: ["stance"],
    tags: [],
    desc: "СТОЙКА ~ При атаке по врагу вы можете: сделать вашу атаку отравленной ядом ИЛИ сбросив две карты, сделать врага беззащитным от атаки.",
    img: "cards/card_63_assassin.png"
  },

  // ── МОДИФИКАТОРЫ (стр. 10–11) ─────────────────────────────────────
  {
    id: 64,
    title: "Флакон яда",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier", "poison"],
    tags: ["poison"],
    desc: "МОДИФИКАТОР ~ Ваша атака теперь накладывает отравление.",
    img: "cards/card_64_flakon_yada.png"
  },
  {
    id: 65,
    title: "Точило",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Ваша атака наносит на одну рану больше.",
    img: "cards/card_65_tochilo.png"
  },
  {
    id: 66,
    title: "Инь и Ян",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: ["trash"],
    desc: "МОДИФИКАТОР ~ Дальность и сила атаки меняются местами.",
    img: "cards/card_66_in_i_yan.png"
  },
  {
    id: 67,
    title: "Удар тени",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Ваша атака игнорирует ловушки.",
    img: "cards/card_67_udar_teni.png"
  },
  {
    id: 68,
    title: "Выпад",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Дальность вашей атаки увеличивается на единицу.",
    img: "cards/card_68_vypad.png"
  },
  {
    id: 69,
    title: "Поступь ветра",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ От вашей атаки невозможно защититься, однако ловушки продолжают действовать.",
    img: "cards/card_69_postup_vetra.png"
  },
  {
    id: 70,
    title: "Гнев сёгуна",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Атаку можно провести даже по обескровленному игроку. Сёгун наносит на одну рану больше.",
    img: "cards/card_70_gnev_syoguna.png"
  },
  {
    id: 71,
    title: "Целебный клинок",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ В случае успешной атаки вы восстанавливаете себе столько жетонов жизни, сколько нанесли ран.",
    img: "cards/card_71_celebnyy_klinok.png"
  },
  {
    id: 72,
    title: "Порыв ярости",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Атака наносит удар по двум целям одновременно. Однако сила и дальность снижаются на один.",
    img: "cards/card_72_poryv_yarosti.png"
  },
  {
    id: 73,
    title: "Повязка камикадзе",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Ваша атака может бить на любом расстоянии и вы наносите на одну рану больше, но вы теряете один жетон жизни. Нельзя применить на пороге смерти.",
    img: "cards/card_73_povyazka_kamikadze.png"
  },
  {
    id: 74,
    title: "Сокрушительный бросок",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Увеличивает дальность атаки на два, но сила атаки (не оружия) становится равна единице. Делает атаку метательной.",
    img: "cards/card_74_sokrushitelnyy_udar.png"
  },
  {
    id: 75,
    title: "Удар камикадзе",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Итоговая сила атаки становится равна вашему количеству жетонов жизни.",
    img: "cards/card_75_brosok.png"
  },
  {
    id: 76,
    title: "Кипящий яд",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Отравленный противник получит на две раны больше.",
    img: "cards/card_76_kipyashchiy_yad.png"
  },
  {
    id: 77,
    title: "Длань сёгуна",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Вы не тратите свою попытку атаки в данном ударе.",
    img: "cards/card_77_dlan_syoguna.png"
  },
  {
    id: 78,
    title: "Дух сёгуна",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ От вашей атаки невозможно защититься, и ловушки не действуют.",
    img: "cards/card_78_dukh_syoguna.png"
  },
  {
    id: 79,
    title: "Пронзительный удар",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Ваша атака оружием полностью игнорирует все бонусы от стойки и персонажа врага.",
    img: "cards/card_80_pronzitelnyy_udar.png"
  },
  {
    id: 80,
    title: "Критический удар",
    types: ["modifier"],
    qty: 1,
    group: "modifier",
    icons: ["modifier"],
    tags: [],
    desc: "МОДИФИКАТОР ~ Ваша базовая сила атаки оружием удваивается.",
    img: "cards/card_79_kriticheskiy_udar.png"
  },

  // ── ГРУППОВЫЕ ДЕЙСТВИЯ (стр. 12) ─────────────────────────────────
  {
    id: 81,
    title: "Целительные источники",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Восстановите два жетона жизни, а все остальные активные игроки один.",
    img: "cards/card_81_celitelnyye_istochniki.png"
  },
  {
    id: 82,
    title: "Миротворцы",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Остальные активные игроки скидывают карту защиты или оружия, либо отдают вам карту из руки на свой выбор.",
    img: "cards/card_82_mirotvortsy.png"
  },
  {
    id: 83,
    title: "Потасовка",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Все активные игроки теряют стойку. Сёгун не участвует в потасовке.",
    img: "cards/card_83_potasovka.png"
  },
  {
    id: 84,
    title: "Чайная церемония",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Вы берёте три карты, остальные активные игроки берут по одной.",
    img: "cards/card_84_chaynaya_tseremoniya.png"
  },
  {
    id: 85,
    title: "Просветление",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Все ловушки на столе открываются, но продолжают действовать.",
    img: "cards/card_85_prosvietlenie.png"
  },
  {
    id: 86,
    title: "Вихрь ярости",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Играется в паре с картой не метательного оружия с дальностью более одного. Минуя ловушки, активные игроки получают урон от оружия (без бонусов) или скидывают защиту. Тратит атаку.",
    img: "cards/card_86_vikhr_yarosti.png"
  },
  {
    id: 87,
    title: "Шквал огня",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Играется в паре с картой метательного оружия. Минуя ловушки, активные игроки получают две раны или скидывают защиту. Тратит атаку.",
    img: "cards/card_86_vikhr_yarosti.png"
  },
  {
    id: 88,
    title: "Бочка зловония",
    types: ["group", "effect"],
    qty: 2,
    group: "group",
    icons: ["aoe", "poison"],
    tags: ["poison"],
    desc: "Все активные игроки получают отравление ядом.",
    img: "cards/card_87_bochka_zlovoniya.png"
  },
  {
    id: 89,
    title: "Град стрел",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Остальные активные игроки скидывают карту оружия или жетон жизни.",
    img: "cards/card_88_grad_strel.png"
  },
  {
    id: 90,
    title: "Боевой крик",
    types: ["group", "action"],
    qty: 1,
    group: "group",
    icons: ["aoe"],
    tags: [],
    desc: "Все ловушки на столе сбрасываются в сброс.",
    img: "cards/card_89_boevoy_krik.png"
  },

  // ── ЭФФЕКТЫ постоянные/разовые (стр. 13–14) ──────────────────────
  {
    id: 91,
    title: "Метка убийцы",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Все атаки по вам наносят на одну рану больше.",
    img: "cards/card_90_metka_ubiytsy.png"
  },
  {
    id: 92,
    title: "Противоядие",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Вас нельзя отравить ядом. Текущее отравление снимается.",
    img: "cards/card_91_protivoyadie.png"
  },
  {
    id: 93,
    title: "Укус змеи",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Каждое лечение по игроку снижается на единицу. Также все негативные эффекты от отравления удваиваются.",
    img: "cards/card_92_ukus_zmeyi.png"
  },
  {
    id: 94,
    title: "Кагинава",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Атаки по вам могут быть произведены без ограничения дальности.",
    img: "cards/card_93_kaginava.png"
  },
  {
    id: 95,
    title: "Разоружение",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Выбранный игрок не может производить прямые атаки оружием.",
    img: "cards/card_94_razoruzhenie.png"
  },
  {
    id: 96,
    title: "Завеса дыма",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "РАЗОВЫЙ эффект. Следующий игровой ход выбранный игрок будто обескровлен.",
    img: "cards/card_95_zavesa_dyma.png"
  },
  {
    id: 97,
    title: "Пыль в глаза",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Атаки игрока не могут бить дальше расстояния в единицу.",
    img: "cards/card_97_pyl_v_glaza.png"
  },
  {
    id: 98,
    title: "Палочка благовоний",
    types: ["effect", "action"],
    qty: 2,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "Выбранный игрок скидывает один выбранный вами эффект. Вы можете восстановить жизнь или взять карту из колоды.",
    img: "cards/card_96_palochka_blagovoniy.png"
  },
  {
    id: 99,
    title: "Чаша благовоний",
    types: ["effect", "action"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "Выбранный игрок скидывает все эффекты. За каждый сброшенный эффект вы можете восстановить жизнь или взять карту из колоды.",
    img: "cards/card_98_chasha_blagovoniy.png"
  },
  {
    id: 100,
    title: "Слабость",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Следующая атака не может нанести более одной раны.",
    img: "cards/card_99_slabost.png"
  },
  {
    id: 101,
    title: "Беззащитность",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Игрок не может защищаться от атак.",
    img: "cards/card_100_bezzashchitnost.png"
  },
  {
    id: 102,
    title: "Дух лидера",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. Выбранный игрок наносит на одну рану больше.",
    img: "cards/card_101_dukh_lidera.png"
  },
  {
    id: 103,
    title: "Бессилие",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "ПОСТОЯННЫЙ эффект. За ход вы можете сделать на одну прямую атаку меньше.",
    img: "cards/card_102_bessilie.png"
  },
  {
    id: 104,
    title: "Эгида",
    types: ["effect"],
    qty: 1,
    group: "effect",
    icons: ["effect8"],
    tags: [],
    desc: "РАЗОВЫЙ эффект. Выбранный игрок автоматически защищается от атаки.",
    img: "cards/card_103_egida.png"
  },

  // ── ДЕЙСТВИЯ (стр. 15–16) ─────────────────────────────────────────
  {
    id: 105,
    title: "Васаби",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Выбранный игрок избавляется от яда и получает жетон жизни.",
    img: "cards/card_104_vasabi.png"
  },
  {
    id: 106,
    title: "Зов предков",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Поменяйте эту карту на любую из сброса не глубже последних 10, но не ранее последних 3.",
    img: "cards/card_105_zov_predkov.png"
  },
  {
    id: 107,
    title: "Швы",
    types: ["action", "effect"],
    qty: 4,
    group: "action",
    icons: [],
    tags: [],
    desc: "Любой выбранный активный игрок восстанавливает два жетона жизни.",
    img: "cards/card_106_shvy.png"
  },
  {
    id: 108,
    title: "Сэппуку",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы умираете и отдаёте жетон чести другому игроку. Таким образом нельзя потерять последний жетон чести.",
    img: "cards/card_107_seppuku.png"
  },
  {
    id: 109,
    title: "Саке",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Можете сбросить эту карту совместно с другими (максимум 3). За каждую сброшенную карту, включая эту, берёте новую карту из колоды.",
    img: "cards/card_108_sake.png"
  },
  {
    id: 110,
    title: "Подсечка",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Другой выбранный игрок скидывает свою текущую стойку, за это вы берёте карту. Или можете сбросить эту карту, чтобы взять две новых из колоды.",
    img: "cards/card_109_podsechka.png"
  },
  {
    id: 111,
    title: "Предательство",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы сбрасываете жетон чести в сброс, и за это получаете семь карт из колоды. Не считается смертью.",
    img: "cards/card_110_predatelstvo.png"
  },
  {
    id: 112,
    title: "Сапёр",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Можете обезвредить любую ловушку на столе, за это вы берёте карту. Или можете сбросить эту карту, чтобы взять две новых из колоды.",
    img: "cards/card_111_sapyor.png"
  },
  {
    id: 113,
    title: "Эквилибриум",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Количество жетонов жизни выбранного игрока становится равно вашему.",
    img: "cards/card_112_ekvilibrium.png"
  },
  {
    id: 114,
    title: "Передышка",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Восстановите все недостающие жетоны стойкости. Другой игрок на ваш выбор берёт одну карту из колоды.",
    img: "cards/card_113_peredyshka.png"
  },
  {
    id: 115,
    title: "Ясновидение",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Выбранный игрок показывает всем свои карты с руки до следующего действия.",
    img: "cards/card_114_yasnovidenie.png"
  },
  {
    id: 116,
    title: "Яд фугу",
    types: ["action", "effect"],
    qty: 1,
    group: "action",
    icons: ["poison"],
    tags: ["poison"],
    desc: "Отравляет выбранного активного игрока. Если игрок уже отравлен, он получает одну рану.",
    img: "cards/card_116_yad_fugu.png"
  },
  {
    id: 117,
    title: "Обмен душ",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы меняетесь с выбранным игроком количеством жетонов жизни.",
    img: "cards/card_115_obmen_dush.png"
  },
  {
    id: 118,
    title: "Дайме",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Либо сыграйте эту карту, чтобы взять три новых из колоды, либо оставьте, чтобы получить победное очко (кроме Ронина).",
    img: "cards/card_117_dayme.png"
  },
  {
    id: 119,
    title: "Переливание крови",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Очищает любого игрока от отравления и передаёт его любому другому.",
    img: "cards/card_118_perelivanie_krovi.png"
  },
  {
    id: 120,
    title: "Жертва крови",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Сыграв эту карту, берите за каждый сброшенный жетон жизни (кроме последнего) новую карту из колоды.",
    img: "cards/card_119_zhertva_krovi.png"
  },

  // ── ВМЕШАТЕЛЬСТВА (стр. 17) ───────────────────────────────────────
  {
    id: 121,
    title: "Исцеление",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. Восстановите все жетоны стойкости отравленному ядом игроку и снимите само отравление.",
    img: "cards/card_120_istselenie.png"
  },
  {
    id: 122,
    title: "Смерть от фугу",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. Сыграйте эту карту, чтобы нанести две раны отравленному ядом игроку.",
    img: "cards/card_121_smert_ot_fugu.png"
  },
  {
    id: 123,
    title: "Имбирь",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. Сыграйте эту карту, чтобы восстановить любому игроку один жетон жизни.",
    img: "cards/card_122_imbir.png"
  },
  {
    id: 124,
    title: "Удар дракона",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. Сыграйте эту карту, чтобы нанести одну рану любому выбранному игроку.",
    img: "cards/card_123_udar_drakona.png"
  },
  {
    id: 125,
    title: "Подвиг",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. Сыграйте эту карту, чтобы перенаправить прямую атаку оружия на себя.",
    img: "cards/card_124_podvig.png"
  },
  {
    id: 126,
    title: "Рука помощи",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. Сыграйте эту карту, чтобы обменяться в закрытую с любым игроком картами на ваше обоюдное усмотрение.",
    img: "cards/card_125_ruka_pomoshchi.png"
  },
  {
    id: 127,
    title: "Весточка",
    types: ["intervention"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. Сыграйте эту карту, чтобы передать любому игроку в закрытую любую другую карту из своей руки.",
    img: "cards/card_126_vestochka.png"
  },
  {
    id: 128,
    title: "Симулянт",
    types: ["intervention", "effect"],
    qty: 1,
    group: "intervention",
    icons: ["intervention"],
    tags: [],
    desc: "ВМЕШАТЕЛЬСТВО. ЭФФЕКТ. Выбранный игрок симулирует смерть, оставляя один жетон жизни. Следующий раунд он обескровлен. В начале хода игрока эффект пропадает. Можно сыграть во время прямой атаки оружием по игроку.",
    img: "cards/card_127_simulyant.png"
  },

  // ── ПРОЧИЕ ДЕЙСТВИЯ (стр. 18) ─────────────────────────────────────
  {
    id: 129,
    title: "Воровство",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Заберите одну случайную карту с руки любого активного игрока.",
    img: "cards/card_128_vorovstvo.png"
  },
  {
    id: 130,
    title: "Кукла вуду",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Можете выбрать любой эффект на столе и переложить его на любого игрока.",
    img: "cards/card_129_kukla_vudu.png"
  },
  {
    id: 131,
    title: "Дурман",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы забираете выбранный эффект игрока на себя.",
    img: "cards/card_130_durman.png"
  },
  {
    id: 132,
    title: "Сифон жизни",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Забираете у игрока жетон жизни и добавляете его себе.",
    img: "cards/card_131_sifon_zhizni.png"
  },
  {
    id: 133,
    title: "Обман",
    types: ["action"],
    qty: 1,
    group: "action",
    icons: [],
    tags: [],
    desc: "Вы забираете ловушку другого игрока себе в руку.",
    img: "cards/card_132_obman.png"
  },

  // ── ПЕРСОНАЖИ (стр. 19) ───────────────────────────────────────────
  {
    id: 134,
    title: "Рюдзо Исикава — Мастер ближнего боя",
    types: ["character"],
    qty: 5,
    group: "character",
    icons: [],
    tags: [],
    desc: "Ваши атаки на расстоянии один наносят на одну рану больше. За каждую рану, полученную от оружия, вы берёте карту из колоды. Раз за ход можете обменять жетоны стойкости на новые карты из колоды.",
    img: "cards/card_133_ryudzo.png"
  },
  {
    id: 135,
    title: "Усивака — Безрассудный налётчик",
    types: ["character"],
    qty: 5,
    group: "character",
    icons: [],
    tags: [],
    desc: "Ваши атаки метательным оружием наносят на одну рану больше. Атаки по вам оружием с дальностью 1 наносят на одну рану меньше. Дайкю не имеет ограничений дальности.",
    img: "cards/card_135_usivaka.png"
  },
  {
    id: 136,
    title: "Таранага Норио — Искусный стратег",
    types: ["character"],
    qty: 5,
    group: "character",
    icons: [],
    tags: [],
    desc: "В фазе набора вы берёте дополнительную карту и можете брать из сброса. В случае воровства, ошеломления или реакции на групповые действия сами выбираете, какую карту отдавать.",
    img: "cards/card_136_taranaga.png"
  },
  {
    id: 137,
    title: "Кокоро — Непоколебимый великан",
    types: ["character"],
    qty: 5,
    group: "character",
    icons: [],
    tags: [],
    desc: "Вашу стойку не могут украсть или сбросить. Вы не теряете стойку при смерти. На вас не действуют карты, заставляющие сбросить случайную карту. Полностью деревянные оружия наносят дополнительную рану.",
    img: "cards/card_138_kokoro.png"
  },
  {
    id: 138,
    title: "Хандзо — Неуловимый синоби",
    types: ["character"],
    qty: 4,
    group: "character",
    icons: [],
    tags: [],
    desc: "Ваши прямые атаки игнорируют ловушки. Вы можете сыграть карту оружия как карту защиты, при этом получая одну рану.",
    img: "cards/card_139_handzo.png"
  },
  {
    id: 139,
    title: "Иё — Знаток ловушек",
    types: ["character"],
    qty: 5,
    group: "character",
    icons: [],
    tags: [],
    desc: "Ваши ловушки не могут обезвредить, украсть или просветить. Вы можете воспользоваться активной ловушкой как защитой, потеряв бонусы от ловушки.",
    img: "cards/card_140_iyo.png"
  },
  {
    id: 140,
    title: "Така — Ловкая воровка",
    types: ["character"],
    qty: 5,
    group: "character",
    icons: [],
    tags: [],
    desc: "Вместо нанесения ран вы можете объявить, что будете воровать карты. Раз в ход вы можете сбросить три карты, чтобы взять две новых из колоды. У вас не могут воровать карты.",
    img: "cards/card_141_taka.png"
  }
];